version: 1.64.7

linters:
  # Enable these linters in addition to the default linters that golangci-lint starts with.
  enable:
    - gofmt
    - gofumpt
    - govet
    - rowserrcheck
    - nilerr
    - nilnesserr
    - errname
    - errorlint
    - errcheck
    - wrapcheck

formatters:
  settings:
    gofmt:
      # Simplify code: gofmt with `-s` option.
      # Default: true
      simplify: false
