version: 1.64.7

linters:
  enable:
    - gofmt
    - gofumpt
    - govet
    - rowserrcheck
    - nilerr
    - nilnesserr
    - errname
    - errorlint
    - errcheck
    - wrapcheck

  settings:
    wrapcheck:
      ignore-sig-regexps:
        - ^Mock.*
        - .*Mock$
        - ^Test.*

formatters:
  settings:
    gofmt:
      simplify: false
