all: false
dir: "{{.InterfaceDir}}"
force-file-write: true
formatter: goimports
log-level: info
structname: "{{.Mock}}{{.InterfaceName}}"
pkgname: "{{.SrcPackageName}}"
filename: "mocks.go"
recursive: false
require-template-schema-exists: true
template: testify
template-schema: "{{.Template}}.schema.json"
packages:
  github.com/stellar/wallet-backend/cmd:
    interfaces:
      ChAccCmdServiceInterface:
  github.com/stellar/wallet-backend/pkg/wbclient/auth:
    interfaces:
      JWTTokenGenerator:
      JWTTokenParser:
  github.com/stellar/wallet-backend/internal/apptracker:
    interfaces:
      AppTracker:
