package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.76

import (
	"context"

	"github.com/stellar/wallet-backend/internal/indexer/types"
	graphql1 "github.com/stellar/wallet-backend/internal/serve/graphql/generated"
)

// Account is the resolver for the account field.
func (r *trustlineBalanceResolver) Account(ctx context.Context, obj *graphql1.TrustlineBalance) (*types.Account, error) {
	return r.models.Account.Get(ctx, obj.Account.StellarAddress)
}

// TrustlineBalance returns graphql1.TrustlineBalanceResolver implementation.
func (r *Resolver) TrustlineBalance() graphql1.TrustlineBalanceResolver {
	return &trustlineBalanceResolver{r}
}

type trustlineBalanceResolver struct{ *Resolver }
