package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"

	"github.com/stellar/wallet-backend/internal/indexer/types"
	graphql1 "github.com/stellar/wallet-backend/internal/serve/graphql/generated"
)

// BlendPositions is the resolver for the blendPositions field.
func (r *accountResolver) BlendPositions(ctx context.Context, obj *types.Account) (*graphql1.BlendAccountPositions, error) {
	return r.getBlendPositions(ctx, string(obj.StellarAddress))
}

// BlendPools is the resolver for the blendPools field.
func (r *queryResolver) BlendPools(ctx context.Context) ([]*graphql1.BlendPool, error) {
	return r.getBlendPools(ctx)
}

// BlendPool is the resolver for the blendPool field.
func (r *queryResolver) BlendPool(ctx context.Context, address string) (*graphql1.BlendPool, error) {
	return r.getBlendPool(ctx, address)
}
