package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"
	"strings"

	"github.com/stellar/wallet-backend/internal/indexer/types"
	"github.com/stellar/wallet-backend/internal/serve/graphql/dataloaders"
	graphql1 "github.com/stellar/wallet-backend/internal/serve/graphql/generated"
	"github.com/stellar/wallet-backend/internal/serve/middleware"
)

// Operations is the resolver for the operations field.
func (r *detailedTransactionEdgeResolver) Operations(ctx context.Context, obj *types.DetailedTransactionEdge) ([]*types.Operation, error) {
	loaders := ctx.Value(middleware.LoadersKey).(*dataloaders.Dataloaders)
	dbColumns := GetDBColumnsForFields(ctx, types.Operation{})
	operations, err := loaders.AccountOperationsByToIDLoader.Load(ctx, dataloaders.OperationColumnsKey{
		ToID:            obj.Node.ToID,
		AccountID:       string(obj.AccountAddress),
		LedgerCreatedAt: obj.Node.LedgerCreatedAt,
		Columns:         strings.Join(dbColumns, ", "),
	})
	if err != nil {
		return nil, err
	}
	return operations, nil
}

// StateChanges is the resolver for the stateChanges field.
func (r *detailedTransactionEdgeResolver) StateChanges(ctx context.Context, obj *types.DetailedTransactionEdge) ([]graphql1.BaseStateChange, error) {
	loaders := ctx.Value(middleware.LoadersKey).(*dataloaders.Dataloaders)
	dbColumns := GetDBColumnsForFields(ctx, types.StateChange{})
	stateChanges, err := loaders.AccountStateChangesByToIDLoader.Load(ctx, dataloaders.StateChangeColumnsKey{
		ToID:            obj.Node.ToID,
		AccountID:       string(obj.AccountAddress),
		LedgerCreatedAt: obj.Node.LedgerCreatedAt,
		Columns:         strings.Join(dbColumns, ", "),
	})
	if err != nil {
		return nil, err
	}
	result := make([]graphql1.BaseStateChange, 0, len(stateChanges))
	for _, sc := range stateChanges {
		result = append(result, convertStateChangeTypes(*sc))
	}
	return result, nil
}

// DetailedTransactionEdge returns graphql1.DetailedTransactionEdgeResolver implementation.
func (r *Resolver) DetailedTransactionEdge() graphql1.DetailedTransactionEdgeResolver {
	return &detailedTransactionEdgeResolver{r}
}

type detailedTransactionEdgeResolver struct{ *Resolver }
