package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"
	"fmt"
	"time"

	"github.com/stellar/wallet-backend/internal/data"
	graphql1 "github.com/stellar/wallet-backend/internal/serve/graphql/generated"
	"github.com/stellar/wallet-backend/internal/services/prices"
	"github.com/stellar/wallet-backend/internal/utils"
)

// TokenPrices is the resolver for the tokenPrices field.
func (r *queryResolver) TokenPrices(ctx context.Context, tokenIds []string) ([]*graphql1.TokenPrice, error) {
	if len(tokenIds) == 0 || len(tokenIds) > maxTokenPriceIDs {
		return nil, badUserInputError(fmt.Sprintf("tokenIds must contain between 1 and %d addresses", maxTokenPriceIDs))
	}
	for _, id := range tokenIds {
		if !utils.IsContractAddress(id) {
			return nil, badUserInputError(errMsgTokenIDInvalid)
		}
	}

	var snap *prices.Snapshot
	if r.config.Prices != nil {
		snap = r.config.Prices.Current()
	}

	out := make([]*graphql1.TokenPrice, len(tokenIds))
	for i, id := range tokenIds {
		out[i] = &graphql1.TokenPrice{TokenID: id}
		if snap == nil {
			continue
		}
		tp, ok := snap.Prices[id]
		if !ok {
			continue
		}
		volume, lastTradeAt := tp.Volume24hUSD, tp.LastTradeAt
		out[i].Volume24hUsd = &volume
		out[i].LastTradeAt = &lastTradeAt
		if !r.config.PublishRule.Publishable(tp, snap.AsOf) {
			continue
		}
		price := tp.PriceUSD
		out[i].PriceUsd = &price
		out[i].PercentChange24h = tp.PercentChange24h()
		switch tp.Source {
		case prices.PriceSourceVWAP1H:
			src := graphql1.TokenPriceSourceVwap1h
			out[i].PriceSource = &src
		case prices.PriceSourceLastTrade:
			src := graphql1.TokenPriceSourceLastTrade
			out[i].PriceSource = &src
		case prices.PriceSourceOracle:
			src := graphql1.TokenPriceSourceOracle
			out[i].PriceSource = &src
		}
	}
	return out, nil
}

// TokenPriceHistory is the resolver for the tokenPriceHistory field.
func (r *queryResolver) TokenPriceHistory(ctx context.Context, tokenID string, resolution graphql1.CandleResolution, from time.Time, to time.Time) ([]*graphql1.Candle, error) {
	if !utils.IsContractAddress(tokenID) {
		return nil, badUserInputError(errMsgTokenIDInvalid)
	}
	if !from.Before(to) {
		return nil, badUserInputError("from must be before to")
	}
	var view string
	var maxSpan time.Duration
	switch resolution {
	case graphql1.CandleResolutionOneMinute:
		view, maxSpan = data.CandleView1m, maxSpanOneMinute
	case graphql1.CandleResolutionOneHour:
		view, maxSpan = data.CandleView1h, maxSpanOneHour
	case graphql1.CandleResolutionOneDay:
		view, maxSpan = data.CandleView1d, maxSpanOneDay
	default:
		return nil, badUserInputError(fmt.Sprintf("unknown resolution %q", resolution))
	}
	if to.Sub(from) > maxSpan {
		return nil, badUserInputError(fmt.Sprintf("span for %s must not exceed %s", resolution, maxSpan))
	}

	candles, err := r.models.Trades.GetCandles(ctx, view, tokenID, from, to, maxCandleBuckets)
	if err != nil {
		return nil, fmt.Errorf("getting candles for %s: %w", tokenID, err)
	}
	out := make([]*graphql1.Candle, len(candles))
	for i, c := range candles {
		out[i] = &graphql1.Candle{
			Bucket:    c.Bucket,
			Open:      c.Open,
			High:      c.High,
			Low:       c.Low,
			Close:     c.Close,
			Vwap:      c.VWAP,
			UsdVolume: c.USDVolume,
			Trades:    int32(c.Trades),
		}
	}
	return out, nil
}
