package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.76

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"strings"
	"sync"

	"github.com/stellar/go-stellar-sdk/xdr"
	"github.com/vektah/gqlparser/v2/gqlerror"

	"github.com/stellar/wallet-backend/internal/data"
	"github.com/stellar/wallet-backend/internal/entities"
	"github.com/stellar/wallet-backend/internal/indexer/types"
	graphql1 "github.com/stellar/wallet-backend/internal/serve/graphql/generated"
	"github.com/stellar/wallet-backend/internal/utils"
)

// TransactionByHash is the resolver for the transactionByHash field.
// This is a root query resolver - it handles the "transactionByHash" query.
// gqlgen calls this function when a GraphQL query requests "transactionByHash"
func (r *queryResolver) TransactionByHash(ctx context.Context, hash string) (*types.Transaction, error) {
	dbColumns := GetDBColumnsForFields(ctx, types.Transaction{})
	return r.models.Transactions.GetByHash(ctx, hash, strings.Join(dbColumns, ", "))
}

// Transactions is the resolver for the transactions field.
// This resolver handles the "transactions" query.
// It demonstrates handling optional arguments (limit can be nil)
func (r *queryResolver) Transactions(ctx context.Context, first *int32, after *string, last *int32, before *string) (*graphql1.TransactionConnection, error) {
	params, err := parsePaginationParams(first, after, last, before, false)
	if err != nil {
		return nil, fmt.Errorf("parsing pagination params: %w", err)
	}
	queryLimit := *params.Limit + 1 // +1 to check if there is a next page

	dbColumns := GetDBColumnsForFields(ctx, types.Transaction{})
	transactions, err := r.models.Transactions.GetAll(ctx, strings.Join(dbColumns, ", "), &queryLimit, params.Cursor, params.SortOrder)
	if err != nil {
		return nil, fmt.Errorf("getting transactions from db: %w", err)
	}

	conn := NewConnectionWithRelayPagination(transactions, params, func(t *types.TransactionWithCursor) int64 {
		return t.Cursor
	})

	edges := make([]*graphql1.TransactionEdge, len(conn.Edges))
	for i, edge := range conn.Edges {
		edges[i] = &graphql1.TransactionEdge{
			Node:   &edge.Node.Transaction,
			Cursor: edge.Cursor,
		}
	}

	return &graphql1.TransactionConnection{
		Edges:    edges,
		PageInfo: conn.PageInfo,
	}, nil
}

// AccountByAddress is the resolver for the accountByAddress field.
func (r *queryResolver) AccountByAddress(ctx context.Context, address string) (*types.Account, error) {
	if address == "" {
		return nil, fmt.Errorf("address cannot be empty")
	}
	acc, err := r.models.Account.Get(ctx, address)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			// If the participant filtering has been enabled and this account is not registered, we return an error.
			if r.config.EnableParticipantFiltering {
				return nil, fmt.Errorf("account not found")
			}

			// When participant filtering is disabled, we return the account object so that the resolver can return a valid object.
			return &types.Account{StellarAddress: address}, nil
		}
		return nil, err
	}
	return acc, nil
}

// Operations is the resolver for the operations field.
// This resolver handles the "operations" query.
func (r *queryResolver) Operations(ctx context.Context, first *int32, after *string, last *int32, before *string) (*graphql1.OperationConnection, error) {
	params, err := parsePaginationParams(first, after, last, before, false)
	if err != nil {
		return nil, fmt.Errorf("parsing pagination params: %w", err)
	}
	queryLimit := *params.Limit + 1 // +1 to check if there is a next page

	dbColumns := GetDBColumnsForFields(ctx, types.Operation{})
	operations, err := r.models.Operations.GetAll(ctx, strings.Join(dbColumns, ", "), &queryLimit, params.Cursor, params.SortOrder)
	if err != nil {
		return nil, fmt.Errorf("getting operations from db: %w", err)
	}

	conn := NewConnectionWithRelayPagination(operations, params, func(o *types.OperationWithCursor) int64 {
		return o.Cursor
	})

	edges := make([]*graphql1.OperationEdge, len(conn.Edges))
	for i, edge := range conn.Edges {
		edges[i] = &graphql1.OperationEdge{
			Node:   &edge.Node.Operation,
			Cursor: edge.Cursor,
		}
	}

	return &graphql1.OperationConnection{
		Edges:    edges,
		PageInfo: conn.PageInfo,
	}, nil
}

// OperationByID is the resolver for the operationById field.
func (r *queryResolver) OperationByID(ctx context.Context, id int64) (*types.Operation, error) {
	dbColumns := GetDBColumnsForFields(ctx, types.Operation{})
	return r.models.Operations.GetByID(ctx, id, strings.Join(dbColumns, ", "))
}

// StateChanges is the resolver for the stateChanges field.
func (r *queryResolver) StateChanges(ctx context.Context, first *int32, after *string, last *int32, before *string) (*graphql1.StateChangeConnection, error) {
	params, err := parsePaginationParams(first, after, last, before, true)
	if err != nil {
		return nil, fmt.Errorf("parsing pagination params: %w", err)
	}
	queryLimit := *params.Limit + 1 // +1 to check if there is a next page

	dbColumns := GetDBColumnsForFields(ctx, types.StateChange{})
	stateChanges, err := r.models.StateChanges.GetAll(ctx, strings.Join(dbColumns, ", "), &queryLimit, params.StateChangeCursor, params.SortOrder)
	if err != nil {
		return nil, fmt.Errorf("getting state changes from db: %w", err)
	}

	convertedStateChanges := convertStateChangeToBaseStateChange(stateChanges)
	conn := NewConnectionWithRelayPagination(convertedStateChanges, params, func(sc *baseStateChangeWithCursor) string {
		return fmt.Sprintf("%d:%d", sc.cursor.ToID, sc.cursor.StateChangeOrder)
	})

	edges := make([]*graphql1.StateChangeEdge, len(conn.Edges))
	for i, edge := range conn.Edges {
		edges[i] = &graphql1.StateChangeEdge{
			Node:   edge.Node.stateChange,
			Cursor: edge.Cursor,
		}
	}

	return &graphql1.StateChangeConnection{
		Edges:    edges,
		PageInfo: conn.PageInfo,
	}, nil
}

// BalancesByAccountAddress is the resolver for the balancesByAccountAddress field.
func (r *queryResolver) BalancesByAccountAddress(ctx context.Context, address string) ([]graphql1.Balance, error) {
	// Validate input: address format
	if !utils.IsValidStellarAddress(address) {
		return nil, &gqlerror.Error{
			Message: ErrMsgSingleInvalidAddress,
			Extensions: map[string]interface{}{
				"code":    "INVALID_ADDRESS",
				"address": address,
			},
		}
	}

	// Build ledger keys: first the account key for native XLM balance
	ledgerKeys := make([]string, 0)

	if !utils.IsContractAddress(address) {
		// Add account ledger key for native XLM balance
		accountKey, err := utils.GetAccountLedgerKey(address)
		if err != nil {
			return nil, &gqlerror.Error{
				Message: ErrMsgBalancesFetchFailed,
				Extensions: map[string]interface{}{
					"code": "INTERNAL_ERROR",
				},
			}
		}
		ledgerKeys = append(ledgerKeys, accountKey)

		// Fetch the current trustlines for the account
		trustlines, err := r.tokenCacheReader.GetAccountTrustlines(ctx, address)
		if err != nil {
			return nil, &gqlerror.Error{
				Message: ErrMsgBalancesFetchFailed,
				Extensions: map[string]interface{}{
					"code": "INTERNAL_ERROR",
				},
			}
		}

		// Build ledger keys for all trustlines
		for _, trustline := range trustlines {
			// Create ledger key for this trustline
			ledgerKey, keyErr := utils.GetTrustlineLedgerKey(address, trustline.Code, trustline.Issuer)
			if keyErr != nil {
				return nil, &gqlerror.Error{
					Message: ErrMsgBalancesFetchFailed,
					Extensions: map[string]interface{}{
						"code": "INTERNAL_ERROR",
					},
				}
			}
			ledgerKeys = append(ledgerKeys, ledgerKey)
		}
	}

	// Fetch the current contracts for the account
	contractIDs, err := r.tokenCacheReader.GetAccountContracts(ctx, address)
	if err != nil {
		return nil, &gqlerror.Error{
			Message: ErrMsgBalancesFetchFailed,
			Extensions: map[string]interface{}{
				"code": "INTERNAL_ERROR",
			},
		}
	}
	contractTokens, err := r.models.Contract.BatchGetByIDs(ctx, contractIDs)
	if err != nil {
		return nil, &gqlerror.Error{
			Message: ErrMsgBalancesFetchFailed,
			Extensions: map[string]interface{}{
				"code": "INTERNAL_ERROR",
			},
		}
	}

	// Build ledger keys for all contracts
	contractsByContractID := make(map[string]*data.Contract)
	sep41TokenIDs := make([]string, 0)
	for _, contract := range contractTokens {
		switch contract.Type {
		case "SAC":
			ledgerKey, keyErr := utils.GetContractDataEntryLedgerKey(address, contract.ID)
			if keyErr != nil {
				return nil, &gqlerror.Error{
					Message: ErrMsgBalancesFetchFailed,
					Extensions: map[string]interface{}{
						"code": "INTERNAL_ERROR",
					},
				}
			}
			ledgerKeys = append(ledgerKeys, ledgerKey)
		case "SEP41":
			sep41TokenIDs = append(sep41TokenIDs, contract.ID)
		default:
			continue
		}
		contractsByContractID[contract.ID] = contract
	}

	// Call RPC to get ledger entries
	ledgerEntriesResult, err := r.rpcService.GetLedgerEntries(ledgerKeys)
	if err != nil {
		return nil, &gqlerror.Error{
			Message: ErrMsgRPCUnavailable,
			Extensions: map[string]interface{}{
				"code": "RPC_UNAVAILABLE",
			},
		}
	}

	networkPassphrase := r.rpcService.NetworkPassphrase()

	var balances []graphql1.Balance
	contractEntriesByContractID := make(map[string]*xdr.ContractDataEntry)
	for _, entry := range ledgerEntriesResult.Entries {
		// Decode the DataXDR to get the ledger entry data
		var ledgerEntryData xdr.LedgerEntryData
		err := xdr.SafeUnmarshalBase64(entry.DataXDR, &ledgerEntryData)
		if err != nil {
			return nil, &gqlerror.Error{
				Message: ErrMsgBalancesFetchFailed,
				Extensions: map[string]interface{}{
					"code": "INTERNAL_ERROR",
				},
			}
		}

		// Check the entry type to determine if it's an account or trustline
		//exhaustive:ignore
		switch ledgerEntryData.Type {
		case xdr.LedgerEntryTypeAccount:
			accountEntry := ledgerEntryData.MustAccount()
			nativeBalance, err := parseNativeBalance(accountEntry, networkPassphrase)
			if err != nil {
				return nil, &gqlerror.Error{
					Message: ErrMsgBalancesFetchFailed,
					Extensions: map[string]interface{}{
						"code": "INTERNAL_ERROR",
					},
				}
			}
			balances = append(balances, nativeBalance)

		case xdr.LedgerEntryTypeTrustline:
			trustlineEntry := ledgerEntryData.MustTrustLine()
			trustlineBalance, err := parseTrustlineBalance(trustlineEntry, entry.LastModifiedLedger, networkPassphrase)
			if err != nil {
				return nil, &gqlerror.Error{
					Message: ErrMsgBalancesFetchFailed,
					Extensions: map[string]interface{}{
						"code": "INTERNAL_ERROR",
					},
				}
			}
			balances = append(balances, trustlineBalance)

		case xdr.LedgerEntryTypeContractData:
			contractDataEntry := ledgerEntryData.MustContractData()

			contractIDStr, ok, err := parseContractIDFromContractData(&contractDataEntry)
			if err != nil {
				return nil, &gqlerror.Error{
					Message: ErrMsgBalancesFetchFailed,
					Extensions: map[string]interface{}{
						"code": "INTERNAL_ERROR",
					},
				}
			}
			if !ok {
				continue
			}

			balance, err := parseSACBalance(&contractDataEntry, contractIDStr, contractsByContractID[contractIDStr])
			if err != nil {
				return nil, &gqlerror.Error{
					Message: ErrMsgBalancesFetchFailed,
					Extensions: map[string]interface{}{
						"code": "INTERNAL_ERROR",
					},
				}
			}
			if balance != nil {
				balances = append(balances, balance)
			}

			contractEntriesByContractID[contractIDStr] = &contractDataEntry
		}
	}

	// Simulate call to `balance(id)` function of SEP-41 contracts
	if len(sep41TokenIDs) > 0 {
		sep41Balances, err := getSep41Balances(ctx, address, r.contractMetadataService, sep41TokenIDs, contractsByContractID, r.pool)
		if err != nil {
			return nil, &gqlerror.Error{
				Message: ErrMsgBalancesFetchFailed,
				Extensions: map[string]interface{}{
					"code": "INTERNAL_ERROR",
				},
			}
		}
		for _, result := range sep41Balances {
			balances = append(balances, result)
		}
	}

	return balances, nil
}

// BalancesByAccountAddresses is the resolver for the balancesByAccountAddresses field.
// It fetches balances for multiple accounts in a single request using parallel processing.
func (r *queryResolver) BalancesByAccountAddresses(ctx context.Context, addresses []string) ([]*graphql1.AccountBalances, error) {
	// Validate input: empty addresses
	if len(addresses) == 0 {
		return nil, &gqlerror.Error{
			Message: ErrMsgEmptyAddresses,
			Extensions: map[string]interface{}{
				"code": "EMPTY_ADDRESSES",
			},
		}
	}

	// Validate input: too many addresses
	if len(addresses) > r.config.MaxAccountsPerBalancesQuery {
		return nil, &gqlerror.Error{
			Message: fmt.Sprintf(ErrMsgTooManyAddresses, r.config.MaxAccountsPerBalancesQuery, len(addresses)),
			Extensions: map[string]interface{}{
				"code":     "TOO_MANY_ADDRESSES",
				"limit":    r.config.MaxAccountsPerBalancesQuery,
				"provided": len(addresses),
			},
		}
	}

	// Deduplicate addresses while preserving order
	seen := make(map[string]bool)
	uniqueAddresses := make([]string, 0, len(addresses))
	for _, addr := range addresses {
		if !seen[addr] {
			seen[addr] = true
			uniqueAddresses = append(uniqueAddresses, addr)
		}
	}
	addresses = uniqueAddresses

	// Validate input: address format
	for i, addr := range addresses {
		if !utils.IsValidStellarAddress(addr) {
			return nil, &gqlerror.Error{
				Message: fmt.Sprintf(ErrMsgInvalidAddressAt, i, addr),
				Extensions: map[string]interface{}{
					"code":    "INVALID_ADDRESS",
					"index":   i,
					"address": addr,
				},
			}
		}
	}

	// Phase 1: Parallel collection of trustlines/contracts for each account
	accountInfos := make([]*accountKeyInfo, len(addresses))
	group := r.pool.NewGroupContext(ctx)

	for idx, addr := range addresses {
		index := idx
		address := addr
		group.Submit(func() {
			info := &accountKeyInfo{
				address:          address,
				isContract:       utils.IsContractAddress(address),
				contractsByID:    make(map[string]*data.Contract),
				sep41ContractIDs: make([]string, 0),
			}

			// Get trustlines (skip for contract addresses)
			if !info.isContract {
				trustlines, err := r.tokenCacheReader.GetAccountTrustlines(ctx, address)
				if err != nil {
					info.collectionErr = fmt.Errorf("getting trustlines: %w", err)
					accountInfos[index] = info
					return
				}
				info.trustlines = trustlines
			}

			// Get contract IDs for the account: note that this also contains contract tokens that we currently dont support (non SEP-41)
			contractIDs, err := r.tokenCacheReader.GetAccountContracts(ctx, address)
			if err != nil {
				info.collectionErr = fmt.Errorf("getting contracts: %w", err)
				accountInfos[index] = info
				return
			}

			// Get contract metadata: note that this will always return only the supported tokens irrespective of non-supported contract IDs
			if len(contractIDs) > 0 {
				contracts, contractErr := r.models.Contract.BatchGetByIDs(ctx, contractIDs)
				if contractErr != nil {
					info.collectionErr = fmt.Errorf("getting contract metadata: %w", contractErr)
					accountInfos[index] = info
					return
				}
				for _, c := range contracts {
					info.contractsByID[c.ID] = c
				}
			}

			accountInfos[index] = info
		})
	}

	if err := group.Wait(); err != nil {
		return nil, &gqlerror.Error{
			Message: ErrMsgBalancesFetchFailed,
			Extensions: map[string]interface{}{
				"code": "INTERNAL_ERROR",
			},
		}
	}

	// Build all ledger keys (sequential - fast operation)
	ledgerKeys := make([]string, 0)
	for _, info := range accountInfos {
		if info.collectionErr != nil {
			continue // Skip accounts with collection errors
		}

		// Build ledger keys for this account
		if !info.isContract {
			// Add account ledger key for native XLM balance
			accountKey, err := utils.GetAccountLedgerKey(info.address)
			if err != nil {
				info.collectionErr = fmt.Errorf("creating account ledger key: %w", err)
				continue
			}
			ledgerKeys = append(ledgerKeys, accountKey)
			info.ledgerKeys = append(info.ledgerKeys, accountKey)

			// Build ledger keys for all trustlines
			for _, trustline := range info.trustlines {
				ledgerKey, keyErr := utils.GetTrustlineLedgerKey(info.address, trustline.Code, trustline.Issuer)
				if keyErr != nil {
					info.collectionErr = fmt.Errorf("creating trustline ledger key for %s-%s: %w", trustline.Code, trustline.Issuer, keyErr)
					break
				}
				ledgerKeys = append(ledgerKeys, ledgerKey)
				info.ledgerKeys = append(info.ledgerKeys, ledgerKey)
			}
		}

		if info.collectionErr != nil {
			continue
		}

		// Build ledger keys for all SAC contracts
		for _, contract := range info.contractsByID {
			switch contract.Type {
			case "SAC":
				ledgerKey, keyErr := utils.GetContractDataEntryLedgerKey(info.address, contract.ID)
				if keyErr != nil {
					info.collectionErr = fmt.Errorf("creating contract ledger key for %s: %w", contract.ID, keyErr)
					break
				}
				ledgerKeys = append(ledgerKeys, ledgerKey)
				info.ledgerKeys = append(info.ledgerKeys, ledgerKey)
			case "SEP41":
				info.sep41ContractIDs = append(info.sep41ContractIDs, contract.ID)
			default:
				continue
			}
		}
	}

	// Single RPC call for all ledger entries
	var rpcResult entities.RPCGetLedgerEntriesResult
	var rpcErr error
	if len(ledgerKeys) > 0 {
		rpcResult, rpcErr = r.rpcService.GetLedgerEntries(ledgerKeys)
		if rpcErr != nil {
			return nil, &gqlerror.Error{
				Message: ErrMsgRPCUnavailable,
				Extensions: map[string]interface{}{
					"code": "RPC_UNAVAILABLE",
				},
			}
		}
	}

	// Create mapping: ledger key -> entry result
	ledgerEntriesByLedgerKeys := make(map[string]*entities.LedgerEntryResult)
	for _, entry := range rpcResult.Entries {
		ledgerEntriesByLedgerKeys[entry.KeyXDR] = &entry
	}

	// Phase 2: Parallel processing of results per account
	networkPassphrase := r.rpcService.NetworkPassphrase()
	results := make([]*graphql1.AccountBalances, len(addresses))
	group = r.pool.NewGroupContext(ctx)
	var resultsMu sync.Mutex

	for idx, info := range accountInfos {
		index := idx
		info := info
		group.Submit(func() {
			result := &graphql1.AccountBalances{
				Address:  info.address,
				Balances: []graphql1.Balance{},
			}

			// Check for collection errors
			if info.collectionErr != nil {
				errStr := info.collectionErr.Error()
				result.Error = &errStr
				resultsMu.Lock()
				results[index] = result
				resultsMu.Unlock()
				return
			}

			// Check for RPC error
			if rpcErr != nil {
				errStr := fmt.Sprintf("RPC error: %v", rpcErr)
				result.Error = &errStr
				resultsMu.Lock()
				results[index] = result
				resultsMu.Unlock()
				return
			}

			// Parse ledger entries for this account
			balances, parseErr := parseAccountBalances(ctx, info, ledgerEntriesByLedgerKeys, r.contractMetadataService, networkPassphrase, r.pool)
			if parseErr != nil {
				errStr := fmt.Sprintf("parsing account balances: %v", parseErr)
				result.Error = &errStr
			} else {
				result.Balances = balances
			}

			resultsMu.Lock()
			results[index] = result
			resultsMu.Unlock()
		})
	}

	if err := group.Wait(); err != nil {
		return nil, &gqlerror.Error{
			Message: ErrMsgBalancesFetchFailed,
			Extensions: map[string]interface{}{
				"code": "INTERNAL_ERROR",
			},
		}
	}

	return results, nil
}

// Query returns graphql1.QueryResolver implementation.
func (r *Resolver) Query() graphql1.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
