package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"
	"strings"

	"github.com/vektah/gqlparser/v2/gqlerror"

	"github.com/stellar/wallet-backend/internal/indexer/types"
	graphql1 "github.com/stellar/wallet-backend/internal/serve/graphql/generated"
	"github.com/stellar/wallet-backend/internal/utils"
)

// TransactionByHash is the resolver for the transactionByHash field.
// This is a root query resolver - it handles the "transactionByHash" query.
// gqlgen calls this function when a GraphQL query requests "transactionByHash"
func (r *queryResolver) TransactionByHash(ctx context.Context, hash string) (*types.Transaction, error) {
	if !utils.IsValidTransactionHash(hash) {
		return nil, &gqlerror.Error{
			Message: ErrMsgInvalidTransactionHash,
			Extensions: map[string]interface{}{
				"code": "INVALID_TRANSACTION_HASH",
				"hash": hash,
			},
		}
	}
	dbColumns := GetDBColumnsForFields(ctx, types.Transaction{})
	return r.models.Transactions.GetByHash(ctx, hash, strings.Join(dbColumns, ", "))
}

// AccountByAddress is the resolver for the accountByAddress field.
func (r *queryResolver) AccountByAddress(ctx context.Context, address string) (*types.Account, error) {
	if !utils.IsValidStellarAddress(address) {
		return nil, &gqlerror.Error{
			Message: ErrMsgSingleInvalidAddress,
			Extensions: map[string]interface{}{
				"code":    "INVALID_ADDRESS",
				"address": address,
			},
		}
	}
	return &types.Account{StellarAddress: types.AddressBytea(address)}, nil
}

// OperationByID is the resolver for the operationById field.
func (r *queryResolver) OperationByID(ctx context.Context, id int64) (*types.Operation, error) {
	dbColumns := GetDBColumnsForFields(ctx, types.Operation{})
	return r.models.Operations.GetByID(ctx, id, strings.Join(dbColumns, ", "))
}

// Query returns graphql1.QueryResolver implementation.
func (r *Resolver) Query() graphql1.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
