package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.76

import (
	"context"
	"fmt"

	"github.com/stellar/wallet-backend/internal/indexer/types"
	graphql1 "github.com/stellar/wallet-backend/internal/serve/graphql/generated"
)

// Type is the resolver for the type field.
func (r *accountStateChangeResolver) Type(ctx context.Context, obj *types.AccountStateChangeModel) (types.StateChangeCategory, error) {
	panic(fmt.Errorf("not implemented: Type - type"))
}

// Reason is the resolver for the reason field.
func (r *accountStateChangeResolver) Reason(ctx context.Context, obj *types.AccountStateChangeModel) (types.StateChangeReason, error) {
	panic(fmt.Errorf("not implemented: Reason - reason"))
}

// Account is the resolver for the account field.
func (r *accountStateChangeResolver) Account(ctx context.Context, obj *types.AccountStateChangeModel) (*types.Account, error) {
	panic(fmt.Errorf("not implemented: Account - account"))
}

// Operation is the resolver for the operation field.
func (r *accountStateChangeResolver) Operation(ctx context.Context, obj *types.AccountStateChangeModel) (*types.Operation, error) {
	panic(fmt.Errorf("not implemented: Operation - operation"))
}

// Transaction is the resolver for the transaction field.
func (r *accountStateChangeResolver) Transaction(ctx context.Context, obj *types.AccountStateChangeModel) (*types.Transaction, error) {
	panic(fmt.Errorf("not implemented: Transaction - transaction"))
}

// TokenID is the resolver for the tokenId field.
func (r *accountStateChangeResolver) TokenID(ctx context.Context, obj *types.AccountStateChangeModel) (string, error) {
	panic(fmt.Errorf("not implemented: TokenID - tokenId"))
}

// Amount is the resolver for the amount field.
func (r *accountStateChangeResolver) Amount(ctx context.Context, obj *types.AccountStateChangeModel) (string, error) {
	panic(fmt.Errorf("not implemented: Amount - amount"))
}

// Type is the resolver for the type field.
func (r *balanceAuthorizationStateChangeResolver) Type(ctx context.Context, obj *types.BalanceAuthorizationStateChangeModel) (types.StateChangeCategory, error) {
	panic(fmt.Errorf("not implemented: Type - type"))
}

// Reason is the resolver for the reason field.
func (r *balanceAuthorizationStateChangeResolver) Reason(ctx context.Context, obj *types.BalanceAuthorizationStateChangeModel) (types.StateChangeReason, error) {
	panic(fmt.Errorf("not implemented: Reason - reason"))
}

// Account is the resolver for the account field.
func (r *balanceAuthorizationStateChangeResolver) Account(ctx context.Context, obj *types.BalanceAuthorizationStateChangeModel) (*types.Account, error) {
	panic(fmt.Errorf("not implemented: Account - account"))
}

// Operation is the resolver for the operation field.
func (r *balanceAuthorizationStateChangeResolver) Operation(ctx context.Context, obj *types.BalanceAuthorizationStateChangeModel) (*types.Operation, error) {
	panic(fmt.Errorf("not implemented: Operation - operation"))
}

// Transaction is the resolver for the transaction field.
func (r *balanceAuthorizationStateChangeResolver) Transaction(ctx context.Context, obj *types.BalanceAuthorizationStateChangeModel) (*types.Transaction, error) {
	panic(fmt.Errorf("not implemented: Transaction - transaction"))
}

// Flags is the resolver for the flags field.
func (r *balanceAuthorizationStateChangeResolver) Flags(ctx context.Context, obj *types.BalanceAuthorizationStateChangeModel) ([]string, error) {
	panic(fmt.Errorf("not implemented: Flags - flags"))
}

// Type is the resolver for the type field.
func (r *balanceStateChangeResolver) Type(ctx context.Context, obj *types.BalanceStateChangeModel) (types.StateChangeCategory, error) {
	return obj.StateChangeCategory, nil
}

// Reason is the resolver for the reason field.
func (r *balanceStateChangeResolver) Reason(ctx context.Context, obj *types.BalanceStateChangeModel) (types.StateChangeReason, error) {
	panic(fmt.Errorf("not implemented: Reason - reason"))
}

// Account is the resolver for the account field.
func (r *balanceStateChangeResolver) Account(ctx context.Context, obj *types.BalanceStateChangeModel) (*types.Account, error) {
	return r.resolveStateChangeAccount(ctx, obj.ToID, obj.StateChangeOrder)
}

// Operation is the resolver for the operation field.
func (r *balanceStateChangeResolver) Operation(ctx context.Context, obj *types.BalanceStateChangeModel) (*types.Operation, error) {
	return r.resolveStateChangeOperation(ctx, obj.ToID, obj.StateChangeOrder)
}

// Transaction is the resolver for the transaction field.
func (r *balanceStateChangeResolver) Transaction(ctx context.Context, obj *types.BalanceStateChangeModel) (*types.Transaction, error) {
	return r.resolveStateChangeTransaction(ctx, obj.ToID, obj.StateChangeOrder)
}

// TokenID is the resolver for the tokenId field.
func (r *balanceStateChangeResolver) TokenID(ctx context.Context, obj *types.BalanceStateChangeModel) (string, error) {
	return r.resolveRequiredString(obj.TokenID), nil
}

// Amount is the resolver for the amount field.
func (r *balanceStateChangeResolver) Amount(ctx context.Context, obj *types.BalanceStateChangeModel) (string, error) {
	return r.resolveRequiredString(obj.Amount), nil
}

// Type is the resolver for the type field.
func (r *flagsStateChangeResolver) Type(ctx context.Context, obj *types.FlagsStateChangeModel) (types.StateChangeCategory, error) {
	return obj.StateChangeCategory, nil
}

// Reason is the resolver for the reason field.
func (r *flagsStateChangeResolver) Reason(ctx context.Context, obj *types.FlagsStateChangeModel) (types.StateChangeReason, error) {
	return *obj.StateChangeReason, nil
}

// Account is the resolver for the account field.
func (r *flagsStateChangeResolver) Account(ctx context.Context, obj *types.FlagsStateChangeModel) (*types.Account, error) {
	return r.resolveStateChangeAccount(ctx, obj.ToID, obj.StateChangeOrder)
}

// Operation is the resolver for the operation field.
func (r *flagsStateChangeResolver) Operation(ctx context.Context, obj *types.FlagsStateChangeModel) (*types.Operation, error) {
	return r.resolveStateChangeOperation(ctx, obj.ToID, obj.StateChangeOrder)
}

// Transaction is the resolver for the transaction field.
func (r *flagsStateChangeResolver) Transaction(ctx context.Context, obj *types.FlagsStateChangeModel) (*types.Transaction, error) {
	return r.resolveStateChangeTransaction(ctx, obj.ToID, obj.StateChangeOrder)
}

// Flags is the resolver for the flags field.
func (r *flagsStateChangeResolver) Flags(ctx context.Context, obj *types.FlagsStateChangeModel) ([]string, error) {
	return r.resolveStringArray([]string(obj.Flags)), nil
}

// Type is the resolver for the type field.
func (r *metadataStateChangeResolver) Type(ctx context.Context, obj *types.MetadataStateChangeModel) (types.StateChangeCategory, error) {
	return obj.StateChangeCategory, nil
}

// Reason is the resolver for the reason field.
func (r *metadataStateChangeResolver) Reason(ctx context.Context, obj *types.MetadataStateChangeModel) (types.StateChangeReason, error) {
	return *obj.StateChangeReason, nil
}

// Account is the resolver for the account field.
func (r *metadataStateChangeResolver) Account(ctx context.Context, obj *types.MetadataStateChangeModel) (*types.Account, error) {
	return r.resolveStateChangeAccount(ctx, obj.ToID, obj.StateChangeOrder)
}

// Operation is the resolver for the operation field.
func (r *metadataStateChangeResolver) Operation(ctx context.Context, obj *types.MetadataStateChangeModel) (*types.Operation, error) {
	return r.resolveStateChangeOperation(ctx, obj.ToID, obj.StateChangeOrder)
}

// Transaction is the resolver for the transaction field.
func (r *metadataStateChangeResolver) Transaction(ctx context.Context, obj *types.MetadataStateChangeModel) (*types.Transaction, error) {
	return r.resolveStateChangeTransaction(ctx, obj.ToID, obj.StateChangeOrder)
}

// KeyValue is the resolver for the keyValue field.
func (r *metadataStateChangeResolver) KeyValue(ctx context.Context, obj *types.MetadataStateChangeModel) (string, error) {
	return r.resolveRequiredJSONBField(obj.KeyValue)
}

// Type is the resolver for the type field.
func (r *signerStateChangeResolver) Type(ctx context.Context, obj *types.SignerStateChangeModel) (types.StateChangeCategory, error) {
	return obj.StateChangeCategory, nil
}

// Reason is the resolver for the reason field.
func (r *signerStateChangeResolver) Reason(ctx context.Context, obj *types.SignerStateChangeModel) (types.StateChangeReason, error) {
	return *obj.StateChangeReason, nil
}

// Account is the resolver for the account field.
func (r *signerStateChangeResolver) Account(ctx context.Context, obj *types.SignerStateChangeModel) (*types.Account, error) {
	return r.resolveStateChangeAccount(ctx, obj.ToID, obj.StateChangeOrder)
}

// Operation is the resolver for the operation field.
func (r *signerStateChangeResolver) Operation(ctx context.Context, obj *types.SignerStateChangeModel) (*types.Operation, error) {
	return r.resolveStateChangeOperation(ctx, obj.ToID, obj.StateChangeOrder)
}

// Transaction is the resolver for the transaction field.
func (r *signerStateChangeResolver) Transaction(ctx context.Context, obj *types.SignerStateChangeModel) (*types.Transaction, error) {
	return r.resolveStateChangeTransaction(ctx, obj.ToID, obj.StateChangeOrder)
}

// SignerAddress is the resolver for the signerAddress field.
func (r *signerStateChangeResolver) SignerAddress(ctx context.Context, obj *types.SignerStateChangeModel) (*string, error) {
	return r.resolveNullableString(obj.SignerAccountID), nil
}

// SignerWeights is the resolver for the signerWeights field.
func (r *signerStateChangeResolver) SignerWeights(ctx context.Context, obj *types.SignerStateChangeModel) (*string, error) {
	return r.resolveJSONBField(obj.SignerWeights)
}

// Type is the resolver for the type field.
func (r *signerThresholdsStateChangeResolver) Type(ctx context.Context, obj *types.SignerThresholdsStateChangeModel) (types.StateChangeCategory, error) {
	return obj.StateChangeCategory, nil
}

// Reason is the resolver for the reason field.
func (r *signerThresholdsStateChangeResolver) Reason(ctx context.Context, obj *types.SignerThresholdsStateChangeModel) (types.StateChangeReason, error) {
	return *obj.StateChangeReason, nil
}

// Account is the resolver for the account field.
func (r *signerThresholdsStateChangeResolver) Account(ctx context.Context, obj *types.SignerThresholdsStateChangeModel) (*types.Account, error) {
	return r.resolveStateChangeAccount(ctx, obj.ToID, obj.StateChangeOrder)
}

// Operation is the resolver for the operation field.
func (r *signerThresholdsStateChangeResolver) Operation(ctx context.Context, obj *types.SignerThresholdsStateChangeModel) (*types.Operation, error) {
	return r.resolveStateChangeOperation(ctx, obj.ToID, obj.StateChangeOrder)
}

// Transaction is the resolver for the transaction field.
func (r *signerThresholdsStateChangeResolver) Transaction(ctx context.Context, obj *types.SignerThresholdsStateChangeModel) (*types.Transaction, error) {
	return r.resolveStateChangeTransaction(ctx, obj.ToID, obj.StateChangeOrder)
}

// Thresholds is the resolver for the thresholds field.
func (r *signerThresholdsStateChangeResolver) Thresholds(ctx context.Context, obj *types.SignerThresholdsStateChangeModel) (string, error) {
	return r.resolveRequiredJSONBField(obj.Thresholds)
}

// Type is the resolver for the type field.
func (r *sponsorshipStateChangeResolver) Type(ctx context.Context, obj *types.SponsorshipStateChangeModel) (types.StateChangeCategory, error) {
	return obj.StateChangeCategory, nil
}

// Reason is the resolver for the reason field.
func (r *sponsorshipStateChangeResolver) Reason(ctx context.Context, obj *types.SponsorshipStateChangeModel) (types.StateChangeReason, error) {
	return *obj.StateChangeReason, nil
}

// Account is the resolver for the account field.
func (r *sponsorshipStateChangeResolver) Account(ctx context.Context, obj *types.SponsorshipStateChangeModel) (*types.Account, error) {
	return r.resolveStateChangeAccount(ctx, obj.ToID, obj.StateChangeOrder)
}

// Operation is the resolver for the operation field.
func (r *sponsorshipStateChangeResolver) Operation(ctx context.Context, obj *types.SponsorshipStateChangeModel) (*types.Operation, error) {
	return r.resolveStateChangeOperation(ctx, obj.ToID, obj.StateChangeOrder)
}

// Transaction is the resolver for the transaction field.
func (r *sponsorshipStateChangeResolver) Transaction(ctx context.Context, obj *types.SponsorshipStateChangeModel) (*types.Transaction, error) {
	return r.resolveStateChangeTransaction(ctx, obj.ToID, obj.StateChangeOrder)
}

// SponsoredAddress is the resolver for the sponsoredAddress field.
func (r *sponsorshipStateChangeResolver) SponsoredAddress(ctx context.Context, obj *types.SponsorshipStateChangeModel) (*string, error) {
	return r.resolveNullableString(obj.SponsoredAccountID), nil
}

// SponsorAddress is the resolver for the sponsorAddress field.
func (r *sponsorshipStateChangeResolver) SponsorAddress(ctx context.Context, obj *types.SponsorshipStateChangeModel) (*string, error) {
	return r.resolveNullableString(obj.SponsorAccountID), nil
}

// Type is the resolver for the type field.
func (r *trustlineStateChangeResolver) Type(ctx context.Context, obj *types.TrustlineStateChangeModel) (types.StateChangeCategory, error) {
	panic(fmt.Errorf("not implemented: Type - type"))
}

// Reason is the resolver for the reason field.
func (r *trustlineStateChangeResolver) Reason(ctx context.Context, obj *types.TrustlineStateChangeModel) (types.StateChangeReason, error) {
	panic(fmt.Errorf("not implemented: Reason - reason"))
}

// Account is the resolver for the account field.
func (r *trustlineStateChangeResolver) Account(ctx context.Context, obj *types.TrustlineStateChangeModel) (*types.Account, error) {
	panic(fmt.Errorf("not implemented: Account - account"))
}

// Operation is the resolver for the operation field.
func (r *trustlineStateChangeResolver) Operation(ctx context.Context, obj *types.TrustlineStateChangeModel) (*types.Operation, error) {
	panic(fmt.Errorf("not implemented: Operation - operation"))
}

// Transaction is the resolver for the transaction field.
func (r *trustlineStateChangeResolver) Transaction(ctx context.Context, obj *types.TrustlineStateChangeModel) (*types.Transaction, error) {
	panic(fmt.Errorf("not implemented: Transaction - transaction"))
}

// Limit is the resolver for the limit field.
func (r *trustlineStateChangeResolver) Limit(ctx context.Context, obj *types.TrustlineStateChangeModel) (string, error) {
	panic(fmt.Errorf("not implemented: Limit - limit"))
}

// AccountStateChange returns graphql1.AccountStateChangeResolver implementation.
func (r *Resolver) AccountStateChange() graphql1.AccountStateChangeResolver {
	return &accountStateChangeResolver{r}
}

// BalanceAuthorizationStateChange returns graphql1.BalanceAuthorizationStateChangeResolver implementation.
func (r *Resolver) BalanceAuthorizationStateChange() graphql1.BalanceAuthorizationStateChangeResolver {
	return &balanceAuthorizationStateChangeResolver{r}
}

// BalanceStateChange returns graphql1.BalanceStateChangeResolver implementation.
func (r *Resolver) BalanceStateChange() graphql1.BalanceStateChangeResolver {
	return &balanceStateChangeResolver{r}
}

// FlagsStateChange returns graphql1.FlagsStateChangeResolver implementation.
func (r *Resolver) FlagsStateChange() graphql1.FlagsStateChangeResolver {
	return &flagsStateChangeResolver{r}
}

// MetadataStateChange returns graphql1.MetadataStateChangeResolver implementation.
func (r *Resolver) MetadataStateChange() graphql1.MetadataStateChangeResolver {
	return &metadataStateChangeResolver{r}
}

// SignerStateChange returns graphql1.SignerStateChangeResolver implementation.
func (r *Resolver) SignerStateChange() graphql1.SignerStateChangeResolver {
	return &signerStateChangeResolver{r}
}

// SignerThresholdsStateChange returns graphql1.SignerThresholdsStateChangeResolver implementation.
func (r *Resolver) SignerThresholdsStateChange() graphql1.SignerThresholdsStateChangeResolver {
	return &signerThresholdsStateChangeResolver{r}
}

// SponsorshipStateChange returns graphql1.SponsorshipStateChangeResolver implementation.
func (r *Resolver) SponsorshipStateChange() graphql1.SponsorshipStateChangeResolver {
	return &sponsorshipStateChangeResolver{r}
}

// TrustlineStateChange returns graphql1.TrustlineStateChangeResolver implementation.
func (r *Resolver) TrustlineStateChange() graphql1.TrustlineStateChangeResolver {
	return &trustlineStateChangeResolver{r}
}

type (
	accountStateChangeResolver              struct{ *Resolver }
	balanceAuthorizationStateChangeResolver struct{ *Resolver }
	balanceStateChangeResolver              struct{ *Resolver }
	flagsStateChangeResolver                struct{ *Resolver }
	metadataStateChangeResolver             struct{ *Resolver }
	signerStateChangeResolver               struct{ *Resolver }
	signerThresholdsStateChangeResolver     struct{ *Resolver }
	sponsorshipStateChangeResolver          struct{ *Resolver }
	trustlineStateChangeResolver            struct{ *Resolver }
)
