CAPTIVE_CORE_CONFIG_PATH="/config/stellar-core_testnet.cfg"
CAPTIVE_CORE_STORAGE_PATH="/var/lib/stellar/captive-core"
CAPTIVE_CORE_USE_DB=true
STELLAR_CORE_BINARY_PATH="/usr/bin/stellar-core"
ENDPOINT="0.0.0.0:8000"
ADMIN_ENDPOINT="0.0.0.0:6061"
DB_PATH="/var/lib/stellar/stellar-rpc-db.sqlite"
STELLAR_CAPTIVE_CORE_HTTP_PORT=11626
FRIENDBOT_URL="https://friendbot.stellar.org/"
NETWORK_PASSPHRASE="Test SDF Network ; September 2015"
HISTORY_ARCHIVE_URLS="https://history.stellar.org/prd/core-testnet/core_testnet_001,https://history.stellar.org/prd/core-testnet/core_testnet_002,https://history.stellar.org/prd/core-testnet/core_testnet_003"
CHECKPOINT_FREQUENCY=64
HISTORY_RETENTION_WINDOW=2000