// EffectsProcessor processes Stellar transaction effects and extracts state changes for account properties.
// It handles signers, thresholds, flags, home domains, data entries, and sponsorship relationships.
package processors

import (
	"context"
	"encoding/base64"
	"fmt"
	"strconv"

	"github.com/stellar/go/ingest"
	effects "github.com/stellar/go/processors/effects"
	operation_processor "github.com/stellar/go/processors/operation"
	"github.com/stellar/go/xdr"

	"github.com/stellar/go/support/log"

	"github.com/stellar/wallet-backend/internal/indexer/types"
)

const (
	// Threshold array indices for accessing account thresholds
	lowThresholdIndex  = 1
	medThresholdIndex  = 2
	highThresholdIndex = 3
)

var (
	// thresholdToReasonMap maps Stellar effect detail field names to our internal state change reasons
	// for account signature threshold updates (low, medium, high threshold changes)
	thresholdToReasonMap = map[string]types.StateChangeReason{
		"low_threshold":  types.StateChangeReasonLow,
		"med_threshold":  types.StateChangeReasonMedium,
		"high_threshold": types.StateChangeReasonHigh,
	}
	// signerEffectToReasonMap maps Stellar signer effect types to our internal state change reasons
	// for tracking when signers are added, removed, or updated on accounts
	signerEffectToReasonMap = map[int32]types.StateChangeReason{
		int32(effects.EffectSignerCreated): types.StateChangeReasonAdd,
		int32(effects.EffectSignerRemoved): types.StateChangeReasonRemove,
		int32(effects.EffectSignerUpdated): types.StateChangeReasonUpdate,
	}
	// accountFlags defines the Stellar account flags we track for authorization states
	accountFlags = []string{
		"auth_required_flag",
		"auth_revocable_flag",
		"auth_immutable_flag",
		"auth_clawback_enabled_flag",
	}
	// trustlineFlags defines the Stellar trustline flags we track for asset authorization states
	trustlineFlags = []string{
		"authorized_flag",
		"authorized_to_maintain_liabilites",
		"clawback_enabled_flag",
	}
)

// EffectsProcessor processes transaction effects generated by horizon's effects processor and converts them into our internal state changes.
// It focuses on account state changes like signers, thresholds, flags, and sponsorship relationships.
type EffectsProcessor struct {
	networkPassphrase string
}

// NewEffectsProcessor creates a new effects processor for the specified Stellar network.
func NewEffectsProcessor(networkPassphrase string) *EffectsProcessor {
	return &EffectsProcessor{
		networkPassphrase: networkPassphrase,
	}
}

// ProcessOperation extracts effects from a Stellar operation and converts them into state changes.
// It processes account state changes like signer modifications, threshold updates, flag changes,
// home domain updates, data entry changes, and sponsorship relationship modifications.
// Returns a slice of state changes representing various account state changes.
func (p *EffectsProcessor) ProcessOperation(_ context.Context, opWrapper *operation_processor.TransactionOperationWrapper) ([]types.StateChange, error) {
	ledgerCloseTime := opWrapper.Transaction.Ledger.LedgerCloseTime()
	ledgerNumber := opWrapper.Transaction.Ledger.LedgerSequence()
	txHash := opWrapper.Transaction.Result.TransactionHash.HexString()

	// Extract effects from the operation using Stellar SDK
	effectOutputs, err := effects.Effects(opWrapper)
	if err != nil {
		return nil, fmt.Errorf("getting effects for tx: %s, opID: %d, err: %w", txHash, opWrapper.ID(), err)
	}

	// Get operation changes to access old values when needed
	changes, err := opWrapper.Transaction.GetOperationChanges(opWrapper.Index)
	if err != nil {
		return nil, fmt.Errorf("getting operation changes for tx: %s, opID: %d, err: %w", txHash, opWrapper.ID(), err)
	}

	var stateChanges []types.StateChange
	masterBuilder := NewStateChangeBuilder(ledgerNumber, ledgerCloseTime, txHash).WithOperationID(opWrapper.ID())
	// Process each effect and convert to our internal state change representation
	for _, effect := range effectOutputs {
		changeBuilder := masterBuilder.Clone().WithAccount(effect.Address)

		effectType := effects.EffectType(effect.Type)
		// Process different types of effects based on what account property they modify
		//exhaustive:ignore
		switch effectType {
		// Signer effects: track changes to account signers (add/remove/update signer keys and weights)
		case effects.EffectSignerCreated, effects.EffectSignerRemoved, effects.EffectSignerUpdated:
			changeBuilder = changeBuilder.
				WithCategory(types.StateChangeCategorySigner).
				WithReason(signerEffectToReasonMap[effect.Type])
			signerChanges, err := p.parseSigners(changeBuilder, &effect, effectType, changes)
			if err != nil {
				return nil, fmt.Errorf("parsing signer effects: effectType: %s, address: %s, txHash: %s, opID: %d, err: %w", effect.TypeString, effect.Address, txHash, opWrapper.ID(), err)
			}
			stateChanges = append(stateChanges, signerChanges...)

		// Threshold effects: track changes to account signature thresholds (low/medium/high)
		case effects.EffectAccountThresholdsUpdated:
			changeBuilder = changeBuilder.WithCategory(types.StateChangeCategorySignatureThreshold)
			stateChanges = append(stateChanges, p.parseThresholds(changeBuilder, &effect, changes)...)

		// Flag effects: track changes to account authorization flags
		case effects.EffectAccountFlagsUpdated:
			changeBuilder = changeBuilder.WithCategory(types.StateChangeCategoryFlags)
			stateChanges = append(stateChanges, p.parseFlags(accountFlags, changeBuilder, &effect)...)

		// Home domain effects: track changes to account home domain metadata
		case effects.EffectAccountHomeDomainUpdated:
			keyValueMap := p.parseKeyValue(&effect, effectType, changes, "home_domain")
			stateChanges = append(stateChanges, changeBuilder.
				WithCategory(types.StateChangeCategoryMetadata).
				WithReason(types.StateChangeReasonHomeDomain).
				WithKeyValue(keyValueMap).
				Build())

		// Trustline flag effects: track changes to trustline authorization flags
		case effects.EffectTrustlineFlagsUpdated:
			changeBuilder = changeBuilder.WithCategory(types.StateChangeCategoryTrustlineFlags)
			stateChanges = append(stateChanges, p.parseFlags(trustlineFlags, changeBuilder, &effect)...)

		// Data entry effects: track changes to account data entries (key-value storage)
		case effects.EffectDataCreated, effects.EffectDataRemoved, effects.EffectDataUpdated:
			keyValueMap := p.parseKeyValue(&effect, effectType, changes, "name")
			stateChanges = append(stateChanges, changeBuilder.
				WithCategory(types.StateChangeCategoryMetadata).
				WithReason(types.StateChangeReasonDataEntry).
				WithKeyValue(keyValueMap).
				Build())

		// Sponsorship effects: track changes to sponsorship relationships for various ledger entries
		// These effects occur when accounts sponsor or stop sponsoring other accounts' reserves
		case effects.EffectAccountSponsorshipCreated, effects.EffectAccountSponsorshipRemoved, effects.EffectAccountSponsorshipUpdated,
			effects.EffectClaimableBalanceSponsorshipCreated, effects.EffectClaimableBalanceSponsorshipRemoved, effects.EffectClaimableBalanceSponsorshipUpdated,
			effects.EffectDataSponsorshipCreated, effects.EffectDataSponsorshipRemoved, effects.EffectDataSponsorshipUpdated,
			effects.EffectSignerSponsorshipCreated, effects.EffectSignerSponsorshipRemoved, effects.EffectSignerSponsorshipUpdated,
			effects.EffectTrustlineSponsorshipCreated, effects.EffectTrustlineSponsorshipRemoved, effects.EffectTrustlineSponsorshipUpdated:

			sponsorshipChanges, err := p.processSponsorshipEffect(effectType, effect, changeBuilder.Clone(), changes)
			if err != nil {
				return nil, fmt.Errorf("processing sponsorship effect: effectType: %s, address: %s, txHash: %s, opID: %d, err: %w", effect.TypeString, effect.Address, txHash, opWrapper.ID(), err)
			}
			stateChanges = append(stateChanges, sponsorshipChanges...)

		default:
			// Skip effects we don't track (e.g., balance changes, trades, etc.)
			continue
		}
	}

	return stateChanges, nil
}

// processSponsorshipEffect handles sponsorship-related effects and creates appropriate state changes.
// Sponsorship in Stellar allows one account to pay the base reserves for another account's ledger entries.
// This function creates state changes for both the sponsor and the sponsored account/entry.
func (p *EffectsProcessor) processSponsorshipEffect(effectType effects.EffectType, effect effects.EffectOutput, baseBuilder *StateChangeBuilder, changes []ingest.Change) ([]types.StateChange, error) {
	baseBuilder = baseBuilder.WithCategory(types.StateChangeCategorySponsorship)

	var sponsorChanges []types.StateChange
	var targetChange types.StateChange

	// Handle different sponsorship effect types and create appropriate state changes
	//exhaustive:ignore
	switch effectType {
	// Created cases: when sponsorship relationships are established
	case effects.EffectAccountSponsorshipCreated, effects.EffectClaimableBalanceSponsorshipCreated,
		effects.EffectDataSponsorshipCreated, effects.EffectSignerSponsorshipCreated, effects.EffectTrustlineSponsorshipCreated:
		sponsor, err := SafeStringFromDetails(effect.Details, "sponsor")
		if err != nil {
			return nil, fmt.Errorf("extracting sponsor from sponsorship created effect: %w", err)
		}
		sponsorChanges = append(sponsorChanges, p.createSponsorChange(types.StateChangeReasonSet, baseBuilder.Clone(), sponsor, effect.Address))
		targetChange = p.createTargetSponsorshipChange(types.StateChangeReasonSet, sponsor, effectType, effect, baseBuilder.Clone())

	// Removed cases: when sponsorship relationships are terminated
	case effects.EffectAccountSponsorshipRemoved, effects.EffectClaimableBalanceSponsorshipRemoved,
		effects.EffectDataSponsorshipRemoved, effects.EffectSignerSponsorshipRemoved, effects.EffectTrustlineSponsorshipRemoved:
		formerSponsor, err := SafeStringFromDetails(effect.Details, "former_sponsor")
		if err != nil {
			return nil, fmt.Errorf("extracting former sponsor from sponsorship removed effect: %w", err)
		}
		sponsorChanges = append(sponsorChanges, p.createSponsorChange(types.StateChangeReasonRemove, baseBuilder.Clone(), formerSponsor, effect.Address))
		targetChange = p.createTargetSponsorshipChange(types.StateChangeReasonRemove, formerSponsor, effectType, effect, baseBuilder.Clone())

	// Updated cases: when sponsorship relationships are transferred from one sponsor to another
	case effects.EffectAccountSponsorshipUpdated, effects.EffectClaimableBalanceSponsorshipUpdated,
		effects.EffectDataSponsorshipUpdated, effects.EffectSignerSponsorshipUpdated, effects.EffectTrustlineSponsorshipUpdated:
		newSponsor, err := SafeStringFromDetails(effect.Details, "new_sponsor")
		if err != nil {
			return nil, fmt.Errorf("extracting new sponsor from sponsorship updated effect: %w", err)
		}
		formerSponsor, err := SafeStringFromDetails(effect.Details, "former_sponsor")
		if err != nil {
			return nil, fmt.Errorf("extracting former sponsor from sponsorship updated effect: %w", err)
		}
		sponsorChanges = append(sponsorChanges,
			p.createSponsorChange(types.StateChangeReasonSet, baseBuilder.Clone(), newSponsor, effect.Address),
			p.createSponsorChange(types.StateChangeReasonRemove, baseBuilder.Clone(), formerSponsor, effect.Address),
		)
		targetBuilder := baseBuilder.Clone().WithKeyValue(p.parseKeyValue(&effect, effectType, changes, "former_sponsor"))
		targetChange = p.createTargetSponsorshipChange(types.StateChangeReasonUpdate, newSponsor, effectType, effect, targetBuilder)
	}

	return append(sponsorChanges, targetChange), nil
}

// createSponsorChange creates a state change for the sponsor account in a sponsorship relationship.
// This tracks when an account starts, stops, or changes its sponsorship of another account's reserves.
func (p *EffectsProcessor) createSponsorChange(reason types.StateChangeReason, builder *StateChangeBuilder, sponsor string, sponsoredAccountID string) types.StateChange {
	return builder.
		WithReason(reason).
		WithAccount(sponsor).
		WithSponsoredAccountID(sponsoredAccountID).
		Build()
}

// createTargetSponsorshipChange creates a state change for the sponsored account or ledger entry.
// This tracks the target side of sponsorship relationships, including specific entry details like claimable balance IDs.
func (p *EffectsProcessor) createTargetSponsorshipChange(reason types.StateChangeReason, sponsor string, effectType effects.EffectType, effect effects.EffectOutput, builder *StateChangeBuilder) types.StateChange {
	builder = builder.WithReason(reason).WithSponsor(sponsor)

	// Add specific identifiers based on the type of sponsored reserve
	//exhaustive:ignore
	switch effectType {
	// For claimable balance sponsorship, include the balance ID
	case effects.EffectClaimableBalanceSponsorshipCreated, effects.EffectClaimableBalanceSponsorshipUpdated, effects.EffectClaimableBalanceSponsorshipRemoved:
		builder = builder.WithClaimableBalance(effect.Details["balance_id"].(string))
	// For trustline sponsorship, include liquidity pool ID if applicable
	case effects.EffectTrustlineSponsorshipCreated, effects.EffectTrustlineSponsorshipUpdated, effects.EffectTrustlineSponsorshipRemoved:
		if lpID, ok := effect.Details["liquidity_pool_id"]; ok {
			builder = builder.WithLiquidityPool(lpID.(string))
		}
	// For signer sponsorship, include the signer key
	case effects.EffectSignerSponsorshipCreated, effects.EffectSignerSponsorshipUpdated, effects.EffectSignerSponsorshipRemoved:
		builder = builder.WithSigner(effect.Details["signer"].(string), map[string]any{
			"new": 0,
		})
	}

	return builder.Build()
}

// parseKeyValue extracts specified key-value pairs from effect details.
// This is used to capture metadata like home domain values or data entry names and values.
func (p *EffectsProcessor) parseKeyValue(effect *effects.EffectOutput, effectType effects.EffectType, changes []ingest.Change, key string) map[string]any {
	prevLedgerEntryState := p.getPrevLedgerEntryState(effect, xdr.LedgerEntryTypeData, changes)
	keyValueMap := map[string]any{}
	if key == "name" {
		keyName := string(effect.Details[key].(xdr.String64))

		//exhaustive:ignore
		switch effectType {
		case effects.EffectDataCreated:
			if value, ok := effect.Details["value"]; ok {
				keyValueMap[keyName] = map[string]any{
					"new": value,
				}
			}
		case effects.EffectDataUpdated, effects.EffectDataRemoved:
			innerMap := map[string]any{}
			if prevLedgerEntryState != nil {
				oldData := prevLedgerEntryState.Data.MustData().DataValue
				innerMap["old"] = base64.StdEncoding.EncodeToString(oldData)
			}
			if effectType == effects.EffectDataUpdated {
				if value, ok := effect.Details["value"]; ok {
					innerMap["new"] = value
				}
			}
			keyValueMap[keyName] = innerMap
		}
	} else {
		if value, ok := effect.Details[key]; ok {
			keyValueMap[key] = value
		}
	}

	return keyValueMap
}

// parseFlags processes flag-related effects and creates separate state changes for set and cleared flags.
// Stellar flags can be either set (true) or cleared (false), and we track each change separately.
func (p *EffectsProcessor) parseFlags(flags []string, changeBuilder *StateChangeBuilder, effect *effects.EffectOutput) []types.StateChange {
	var setFlags, clearFlags []string

	for _, flag := range flags {
		if value, ok := effect.Details[flag]; ok {
			if value == true {
				setFlags = append(setFlags, flag)
			} else {
				clearFlags = append(clearFlags, flag)
			}
		}
	}

	var changes []types.StateChange
	if len(setFlags) > 0 {
		changes = append(changes, changeBuilder.
			Clone().
			WithReason(types.StateChangeReasonSet).
			WithFlags(setFlags).
			Build())
	}
	if len(clearFlags) > 0 {
		changes = append(changes, changeBuilder.
			Clone().
			WithReason(types.StateChangeReasonClear).
			WithFlags(clearFlags).
			Build())
	}

	return changes
}

func (p *EffectsProcessor) parseSigners(changeBuilder *StateChangeBuilder, effect *effects.EffectOutput, effectType effects.EffectType, changes []ingest.Change) ([]types.StateChange, error) {
	signerPublicKey := effect.Details["public_key"].(string)
	weight, err := ConvertToInt32(effect.Details["weight"])
	if err != nil {
		return nil, fmt.Errorf("converting weight for signer effect: %w", err)
	}

	//exhaustive:ignore
	switch effectType {
	case effects.EffectSignerCreated:
		changeBuilder = changeBuilder.WithSigner(
			signerPublicKey,
			map[string]any{
				"new": weight,
			},
		)
	case effects.EffectSignerUpdated, effects.EffectSignerRemoved:
		weights := map[string]any{}
		prevLedgerEntryState := p.getPrevLedgerEntryState(effect, xdr.LedgerEntryTypeAccount, changes)
		if prevLedgerEntryState != nil {
			prevAccount := prevLedgerEntryState.Data.MustAccount()
			oldSignerSummary := prevAccount.SignerSummary()
			weights["old"] = oldSignerSummary[signerPublicKey]
		} else {
			log.Debugf("no previous account state found for account: %s: opID: %d", effect.Address, effect.OperationID)
		}
		if effectType == effects.EffectSignerUpdated {
			weights["new"] = weight
		}
		changeBuilder = changeBuilder.WithSigner(signerPublicKey, weights)
	}
	return []types.StateChange{changeBuilder.Build()}, nil
}

// parseThresholds processes threshold-related effects and creates state changes for each threshold type.
// It extracts both old and new threshold values from the ledger entry changes.
func (p *EffectsProcessor) parseThresholds(changeBuilder *StateChangeBuilder, effect *effects.EffectOutput, changes []ingest.Change) []types.StateChange {
	// Find the account entry change to get old threshold values
	prevLedgerEntryState := p.getPrevLedgerEntryState(effect, xdr.LedgerEntryTypeAccount, changes)

	// Create a separate state change for each threshold that was modified
	var thresholdChanges []types.StateChange
	for threshold, reason := range thresholdToReasonMap {
		if value, ok := effect.Details[threshold]; ok {
			// Convert XDR threshold value to string for storage
			thresholdValue := strconv.FormatInt(int64(value.(xdr.Uint32)), 10)

			// Create threshold details with both old and new values
			thresholdDetails := map[string]any{
				"new": thresholdValue,
			}

			// Add old threshold value if available
			if prevLedgerEntryState != nil {
				var oldValue string
				prevAccount := prevLedgerEntryState.Data.MustAccount()
				switch threshold {
				case "low_threshold":
					oldValue = strconv.FormatInt(int64(prevAccount.Thresholds[lowThresholdIndex]), 10)
				case "med_threshold":
					oldValue = strconv.FormatInt(int64(prevAccount.Thresholds[medThresholdIndex]), 10)
				case "high_threshold":
					oldValue = strconv.FormatInt(int64(prevAccount.Thresholds[highThresholdIndex]), 10)
				}
				thresholdDetails["old"] = oldValue
			} else {
				log.Debugf("no previous account state found for account: %s: opID: %d", effect.Address, effect.OperationID)
			}

			thresholdChanges = append(thresholdChanges, changeBuilder.
				Clone().
				WithReason(reason).
				WithThresholds(thresholdDetails).
				Build())
		}
	}
	return thresholdChanges
}

// getPrevLedgerEntryState gets the previous ledger entry state for the specified ledger entry type.
func (p *EffectsProcessor) getPrevLedgerEntryState(effect *effects.EffectOutput, ledgerEntryType xdr.LedgerEntryType, changes []ingest.Change) *xdr.LedgerEntry {
	for _, change := range changes {
		if change.Type != ledgerEntryType {
			continue
		}
		if change.Pre != nil {
			beforeEntry := change.Pre
			if beforeEntry != nil {
				if ledgerEntryType == xdr.LedgerEntryTypeAccount {
					beforeAccount := beforeEntry.Data.MustAccount()
					if beforeAccount.AccountId.Address() == effect.Address {
						return beforeEntry
					}
				}
				return beforeEntry
			}
		}
	}
	return nil
}
