// EffectsProcessor processes Stellar transaction effects and extracts state changes for account properties.
// It handles signers, thresholds, flags, home domains, and data entries.
package processors

import (
	"context"
	"encoding/base64"
	"fmt"
	"strconv"
	"time"

	"github.com/stellar/go-stellar-sdk/ingest"
	"github.com/stellar/go-stellar-sdk/xdr"

	"github.com/stellar/go-stellar-sdk/support/log"

	"github.com/stellar/wallet-backend/internal/indexer/types"
	"github.com/stellar/wallet-backend/internal/metrics"
)

const (
	// Threshold array indices for accessing account thresholds
	lowThresholdIndex                       = 1
	medThresholdIndex                       = 2
	highThresholdIndex                      = 3
	AuthorizedFlagName                      = "authorized"
	AuthorizedRequiredFlagName              = "auth_required"
	AuthorizedRevocableFlagName             = "auth_revocable"
	AuthorizedImmutableFlagName             = "auth_immutable"
	AuthorizedClawbackEnabledFlagName       = "auth_clawback_enabled"
	ClawbackEnabledFlagName                 = "clawback_enabled"
	AuthorizedToMaintainLiabilitiesFlagName = "authorized_to_maintain_liabilities"
)

var (
	// thresholdToLevelMap maps Stellar effect detail field names to the ThresholdLevel
	// identifying which of the account's signature thresholds a state change refers to
	thresholdToLevelMap = map[string]types.ThresholdLevel{
		"low_threshold":  types.ThresholdLevelLow,
		"med_threshold":  types.ThresholdLevelMedium,
		"high_threshold": types.ThresholdLevelHigh,
	}
	// thresholdOrder fixes the emission order of threshold state changes so
	// ordinals within a (to_id, operation_id) group are deterministic across runs.
	thresholdOrder = []string{"low_threshold", "med_threshold", "high_threshold"}
	// dataEntryEffectToReasonMap maps data-entry effect types to the state change
	// reason describing the kind of update performed on the entry
	dataEntryEffectToReasonMap = map[EffectType]types.StateChangeReason{
		EffectDataCreated: types.StateChangeReasonAdd,
		EffectDataUpdated: types.StateChangeReasonUpdate,
		EffectDataRemoved: types.StateChangeReasonRemove,
	}
	// signerEffectToReasonMap maps Stellar signer effect types to our internal state change reasons
	// for tracking when signers are added, removed, or updated on accounts
	signerEffectToReasonMap = map[int32]types.StateChangeReason{
		int32(EffectSignerCreated): types.StateChangeReasonAdd,
		int32(EffectSignerRemoved): types.StateChangeReasonRemove,
		int32(EffectSignerUpdated): types.StateChangeReasonUpdate,
	}
	// accountFlags defines the Stellar account flags we track for authorization states
	accountFlags = []string{
		"auth_required",
		"auth_revocable",
		"auth_immutable",
		"auth_clawback_enabled",
	}
	// trustlineFlags defines the Stellar trustline flags we track for asset authorization states
	trustlineFlags = []string{
		"authorized",
		"authorized_to_maintain_liabilities",
		"clawback_enabled",
	}
)

// EffectsProcessor processes transaction effects generated by horizon's effects processor and converts them into our internal state changes.
// It focuses on account state changes like signers, thresholds, and flags.
type EffectsProcessor struct {
	networkPassphrase string
	metricsService    *metrics.IngestionMetrics
	assetContractIDs  AssetContractIDMemo
}

// NewEffectsProcessor creates a new effects processor for the specified Stellar network.
func NewEffectsProcessor(networkPassphrase string, metricsService *metrics.IngestionMetrics) *EffectsProcessor {
	return &EffectsProcessor{
		networkPassphrase: networkPassphrase,
		metricsService:    metricsService,
	}
}

func (p *EffectsProcessor) Name() string {
	return "effects"
}

func (p *EffectsProcessor) StateChangeSubBase() int64 {
	return types.StateChangeSubBaseEffects
}

// ProcessOperation extracts effects from a Stellar operation and converts them into state changes.
// It processes account state changes like signer modifications, threshold updates, flag changes,
// home domain updates, and data entry changes.
// Returns a slice of state changes representing various account state changes.
func (p *EffectsProcessor) ProcessOperation(_ context.Context, opWrapper *TransactionOperationWrapper) ([]types.StateChange, error) {
	startTime := time.Now()
	defer func() {
		if p.metricsService != nil {
			duration := time.Since(startTime).Seconds()
			p.metricsService.StateChangeProcessingDuration.WithLabelValues("EffectsProcessor").Observe(duration)
		}
	}()

	ledgerCloseTime := opWrapper.Transaction.Ledger.LedgerCloseTime()
	ledgerNumber := opWrapper.Transaction.Ledger.LedgerSequence()
	txID := opWrapper.Transaction.ID()

	// Extract effects from the operation using Stellar SDK
	effectOutputs, err := Effects(opWrapper)
	if err != nil {
		return nil, fmt.Errorf("getting effects for tx: %s, opID: %d, err: %w", opWrapper.Transaction.Result.TransactionHash.HexString(), opWrapper.ID(), err)
	}

	// Get operation changes to access old values when needed
	changes, err := opWrapper.Changes()
	if err != nil {
		return nil, fmt.Errorf("getting operation changes for tx: %s, opID: %d, err: %w", opWrapper.Transaction.Result.TransactionHash.HexString(), opWrapper.ID(), err)
	}

	if len(effectOutputs) == 0 {
		return nil, nil
	}

	var stateChanges []types.StateChange
	masterBuilder := NewStateChangeBuilder(ledgerNumber, ledgerCloseTime, txID).WithOperationID(opWrapper.ID())
	// Process each effect and convert to our internal state change representation
	for _, effect := range effectOutputs {
		changeBuilder := masterBuilder.WithAccount(effect.Address)

		effectType := EffectType(effect.Type)
		// Process different types of effects based on what account property they modify
		//exhaustive:ignore
		switch effectType {
		// Signer effects: track changes to account signers (add/remove/update signer keys and weights)
		case EffectSignerCreated, EffectSignerRemoved, EffectSignerUpdated:
			changeBuilder = changeBuilder.
				WithCategory(types.StateChangeCategorySigner).
				WithReason(signerEffectToReasonMap[effect.Type])
			signerChanges, err := p.parseSigners(changeBuilder, &effect, effectType, changes)
			if err != nil {
				log.Warnf("processor: %s: failed to parse signer effects: effectType: %s, address: %s, txHash: %s, opID: %d, err: %v", p.Name(), effect.TypeString, effect.Address, opWrapper.Transaction.Result.TransactionHash.HexString(), opWrapper.ID(), err)
				continue
			}
			stateChanges = append(stateChanges, signerChanges...)

		// Threshold effects: track changes to account signature thresholds (low/medium/high)
		case EffectAccountThresholdsUpdated:
			changeBuilder = changeBuilder.WithCategory(types.StateChangeCategorySignatureThreshold)
			thresholdChanges, err := p.parseThresholds(changeBuilder, &effect, changes)
			if err != nil {
				log.Warnf("processor: %s: failed to parse threshold effects: effectType: %s, address: %s, txHash: %s, opID: %d, err: %v", p.Name(), effect.TypeString, effect.Address, opWrapper.Transaction.Result.TransactionHash.HexString(), opWrapper.ID(), err)
				continue
			}
			stateChanges = append(stateChanges, thresholdChanges...)

		// Flag effects: track changes to account authorization flags
		case EffectAccountFlagsUpdated:
			changeBuilder = changeBuilder.WithCategory(types.StateChangeCategoryFlags)
			stateChanges = append(stateChanges, p.parseFlags(accountFlags, changeBuilder, &effect)...)

		// Home domain effects: track the account's home domain being set, replaced, or removed
		case EffectAccountHomeDomainUpdated:
			oldDomain, newDomain, err := p.parseHomeDomain(&effect, changes)
			if err != nil {
				log.Warnf("processor: %s: failed to parse home domain effect: effectType: %s, address: %s, txHash: %s, opID: %d, err: %v", p.Name(), effect.TypeString, effect.Address, opWrapper.Transaction.Result.TransactionHash.HexString(), opWrapper.ID(), err)
				continue
			}
			reason, keyValueMap, changed := homeDomainChange(oldDomain, newDomain)
			if !changed {
				// The operation wrote the home domain the account already had.
				continue
			}
			stateChanges = append(stateChanges, changeBuilder.
				WithCategory(types.StateChangeCategoryHomeDomain).
				WithReason(reason).
				WithKeyValue(keyValueMap).
				Build())

		// Trustline flag effects: track changes to trustline authorization flags
		case EffectTrustlineFlagsUpdated:
			changeBuilder = changeBuilder.WithCategory(types.StateChangeCategoryBalanceAuthorization)
			// Note: The Stellar SDK sets effect.Address to the operation source (issuer),
			// but the trustline flags are actually being set on the trustor's account.
			// We need to extract the trustor address from effect.Details instead.
			if trustorAddr, err := safeStringFromDetails(effect.Details, "trustor"); err == nil {
				changeBuilder = changeBuilder.WithAccount(trustorAddr)
			}
			// Build the asset contract ID from the trustline effect
			_, _, assetContractID, err := p.buildAssetContractIDFromTrustlineEffect(&effect)
			if err != nil {
				log.Warnf("processor: %s: failed to build asset contract ID from trustline effect: effectType: %s, address: %s, txHash: %s, opID: %d, err: %v", p.Name(), effect.TypeString, effect.Address, opWrapper.Transaction.Result.TransactionHash.HexString(), opWrapper.ID(), err)
				continue
			}
			changeBuilder = changeBuilder.WithToken(assetContractID)
			stateChanges = append(stateChanges, p.parseFlags(trustlineFlags, changeBuilder, &effect)...)

		// Change trust effects
		case EffectTrustlineCreated, EffectTrustlineRemoved, EffectTrustlineUpdated:
			changeBuilder = changeBuilder.WithCategory(types.StateChangeCategoryTrustline)
			trustlineChange, trustlineBuilder, err := p.parseTrustline(changeBuilder, &effect, effectType, changes)
			if err != nil {
				log.Warnf("processor: %s: failed to parse trustline effect: effectType: %s, address: %s, txHash: %s, opID: %d, err: %v", p.Name(), effect.TypeString, effect.Address, opWrapper.Transaction.Result.TransactionHash.HexString(), opWrapper.ID(), err)
				continue
			}
			stateChanges = append(stateChanges, trustlineChange)

			// Generate balance authorization state change for new trustline.
			// We will extract the authorization flags directly from the trustline entry in the changes.
			if effectType == EffectTrustlineCreated {
				authChanges, err := p.generateBalanceAuthorizationForNewTrustline(trustlineBuilder, &effect, changes)
				if err != nil {
					log.Warnf("processor: %s: failed to generate balance authorization for new trustline: effectType: %s, address: %s, txHash: %s, opID: %d, err: %v", p.Name(), effect.TypeString, effect.Address, opWrapper.Transaction.Result.TransactionHash.HexString(), opWrapper.ID(), err)
					continue
				}
				stateChanges = append(stateChanges, authChanges)
			}

		// Data entry effects: track changes to account data entries (key-value storage)
		case EffectDataCreated, EffectDataRemoved, EffectDataUpdated:
			keyValueMap, err := p.parseDataEntryValues(&effect, effectType, changes)
			if err != nil {
				log.Warnf("processor: %s: failed to parse data entry effect: effectType: %s, address: %s, txHash: %s, opID: %d, err: %v", p.Name(), effect.TypeString, effect.Address, opWrapper.Transaction.Result.TransactionHash.HexString(), opWrapper.ID(), err)
				continue
			}
			stateChanges = append(stateChanges, changeBuilder.
				WithCategory(types.StateChangeCategoryDataEntry).
				WithReason(dataEntryEffectToReasonMap[effectType]).
				WithDataEntryName(string(effect.Details["name"].(xdr.String64))).
				WithKeyValue(keyValueMap).
				Build())

		default:
			// Skip effects we don't track (e.g., balance changes, trades, etc.)
			continue
		}
	}

	return stateChanges, nil
}

// parseTrustline builds the trustline state change and returns the builder it was
// built from: the asset (or pool) it resolved and the trustline limits it recorded
// also belong to the balance-authorization change a trustline creation emits.
func (p *EffectsProcessor) parseTrustline(baseBuilder StateChangeBuilder, effect *EffectOutput, effectType EffectType, changes []ingest.Change) (types.StateChange, StateChangeBuilder, error) {
	var assetCode, assetIssuer string
	assetType, err := safeStringFromDetails(effect.Details, "asset_type")
	if err != nil {
		return types.StateChange{}, baseBuilder, fmt.Errorf("extracting asset type from effect details: %w", err)
	}
	if assetType == "liquidity_pool_shares" {
		var poolID string
		poolID, err = safeStringFromDetails(effect.Details, "liquidity_pool_id")
		if err != nil {
			return types.StateChange{}, baseBuilder, fmt.Errorf("extracting liquidity pool ID from effect details: %w", err)
		}

		baseBuilder = baseBuilder.WithLiquidityPoolID(poolID)
	} else {
		assetCode, err = safeStringFromDetails(effect.Details, "asset_code")
		if err != nil {
			return types.StateChange{}, baseBuilder, fmt.Errorf("extracting asset code from effect details: %w", err)
		}
		assetIssuer, err = safeStringFromDetails(effect.Details, "asset_issuer")
		if err != nil {
			return types.StateChange{}, baseBuilder, fmt.Errorf("extracting asset issuer from effect details: %w", err)
		}
		assetContractID, err := p.assetContractIDs.fromDetails(p.networkPassphrase, assetType, assetCode, assetIssuer)
		if err != nil {
			return types.StateChange{}, baseBuilder, fmt.Errorf("parsing asset: %w", err)
		}
		baseBuilder = baseBuilder.WithToken(assetContractID)
	}

	var stateChange types.StateChange

	//exhaustive:ignore
	switch effectType {
	case EffectTrustlineCreated:
		newLimit := fmt.Sprintf("%v", effect.Details["limit"])
		baseBuilder = baseBuilder.WithReason(types.StateChangeReasonAdd).
			WithTrustlineLimit(nil, &newLimit)
		stateChange = baseBuilder.Build()

	case EffectTrustlineRemoved:
		baseBuilder = baseBuilder.WithReason(types.StateChangeReasonRemove)
		stateChange = baseBuilder.Build()

	case EffectTrustlineUpdated:
		// The GraphQL schema declares oldLimit non-null, so the trustline
		// pre-image is required; an update effect without one is malformed.
		prevLedgerEntryState := p.getPrevLedgerEntryState(effect, xdr.LedgerEntryTypeTrustline, changes)
		if prevLedgerEntryState == nil {
			return types.StateChange{}, baseBuilder, fmt.Errorf("no previous trustline state for trustline update on account %s (opID %d)", effect.Address, effect.OperationID)
		}
		prevTrustline := prevLedgerEntryState.Data.MustTrustLine()
		oldLimit := strconv.FormatInt(int64(prevTrustline.Limit), 10)
		newLimit := fmt.Sprintf("%v", effect.Details["limit"])
		baseBuilder = baseBuilder.WithReason(types.StateChangeReasonUpdate).
			WithTrustlineLimit(&oldLimit, &newLimit)
		stateChange = baseBuilder.Build()
	}

	return stateChange, baseBuilder, nil
}

// generateBalanceAuthorizationForNewTrustline generates balance authorization state changes
// for newly created trustlines by reading the trustline flags directly from transaction changes
func (p *EffectsProcessor) generateBalanceAuthorizationForNewTrustline(baseBuilder StateChangeBuilder, effect *EffectOutput, changes []ingest.Change) (types.StateChange, error) {
	// Skip native assets as they don't have authorization
	assetType, err := safeStringFromDetails(effect.Details, "asset_type")
	if err != nil {
		return types.StateChange{}, fmt.Errorf("extracting asset type from effect details: %w", err)
	}
	if assetType == "native" {
		return types.StateChange{}, nil
	}

	var defaultFlags []string
	if assetType == "liquidity_pool_shares" {
		poolID, err := safeStringFromDetails(effect.Details, "liquidity_pool_id")
		if err != nil {
			return types.StateChange{}, fmt.Errorf("extracting liquidity pool ID from effect details: %w", err)
		}
		baseBuilder = baseBuilder.WithLiquidityPoolID(poolID)
	} else {
		assetCode, assetIssuer, assetContractID, err := p.buildAssetContractIDFromTrustlineEffect(effect)
		if err != nil {
			return types.StateChange{}, fmt.Errorf("building asset contract ID from trustline effect: %w", err)
		}
		baseBuilder = baseBuilder.WithToken(assetContractID)

		// Extract trustline flags directly from the transaction changes
		trustlineFlags, err := p.getTrustlineFlagsFromChanges(effect.Address, assetCode, assetIssuer, changes)
		if err != nil {
			return types.StateChange{}, fmt.Errorf("getting trustline flags from changes: %w", err)
		}

		// Map XDR trustline flags to our internal flag representation
		defaultFlags = p.mapTrustlineFlagsToStrings(trustlineFlags)
	}

	// Generate state changes for each flag that should be set
	return baseBuilder.
		WithCategory(types.StateChangeCategoryBalanceAuthorization).
		WithReason(types.StateChangeReasonSet).
		WithFlags(defaultFlags).
		Build(), nil
}

func (p *EffectsProcessor) buildAssetContractIDFromTrustlineEffect(effect *EffectOutput) (string, string, string, error) {
	assetType, err := safeStringFromDetails(effect.Details, "asset_type")
	if err != nil {
		return "", "", "", fmt.Errorf("extracting asset type from effect details: %w", err)
	}
	assetCode, err := safeStringFromDetails(effect.Details, "asset_code")
	if err != nil {
		return "", "", "", fmt.Errorf("extracting asset code from effect details: %w", err)
	}
	assetIssuer, err := safeStringFromDetails(effect.Details, "asset_issuer")
	if err != nil {
		return "", "", "", fmt.Errorf("extracting asset issuer from effect details: %w", err)
	}
	assetContractID, err := p.assetContractIDs.fromDetails(p.networkPassphrase, assetType, assetCode, assetIssuer)
	if err != nil {
		return "", "", "", fmt.Errorf("getting asset contract ID: %w", err)
	}
	return assetCode, assetIssuer, assetContractID, nil
}

// getTrustlineFlagsFromChanges extracts the trustline flags from transaction changes
func (p *EffectsProcessor) getTrustlineFlagsFromChanges(trustorAddress, assetCode, assetIssuer string, changes []ingest.Change) (xdr.TrustLineFlags, error) {
	// Search through changes to find the trustline entry for this specific asset and trustor. Note that these changes
	// are from the specific operation so we will only find the entries for the specific operation and not the entire transaction.
	for _, change := range changes {
		if change.Type != xdr.LedgerEntryTypeTrustline {
			continue
		}

		// Prefer Post state if available (most recent), otherwise use Pre
		var trustlineEntry xdr.TrustLineEntry
		if change.Post != nil {
			trustlineEntry = change.Post.Data.MustTrustLine()
		} else if change.Pre != nil {
			trustlineEntry = change.Pre.Data.MustTrustLine()
		} else {
			continue
		}

		// Match the trustline by trustor address
		if trustlineEntry.AccountId.Address() != trustorAddress {
			continue
		}

		// Match the trustline by asset
		asset := trustlineEntry.Asset

		var entryAssetCode, entryAssetIssuer string
		//exhaustive:ignore
		switch asset.Type {
		case xdr.AssetTypeAssetTypeNative:
			continue
		case xdr.AssetTypeAssetTypeCreditAlphanum4:
			alphaNum4 := asset.MustAlphaNum4()
			assetCodeBytes := alphaNum4.AssetCode[:]
			entryAssetCode = string(assetCodeBytes)
			entryAssetIssuer = alphaNum4.Issuer.Address()
		case xdr.AssetTypeAssetTypeCreditAlphanum12:
			alphaNum12 := asset.MustAlphaNum12()
			assetCodeBytes := alphaNum12.AssetCode[:]
			entryAssetCode = string(assetCodeBytes)
			entryAssetIssuer = alphaNum12.Issuer.Address()
		}

		// Remove null bytes from asset code
		for i, c := range entryAssetCode {
			if c == 0 {
				entryAssetCode = entryAssetCode[:i]
				break
			}
		}

		if entryAssetCode == assetCode && entryAssetIssuer == assetIssuer {
			return xdr.TrustLineFlags(trustlineEntry.Flags), nil
		}
	}

	return 0, fmt.Errorf("trustline not found in changes for trustor: %s, asset: %s:%s", trustorAddress, assetCode, assetIssuer)
}

// mapTrustlineFlagsToStrings converts XDR trustline flags to our internal string representation
func (p *EffectsProcessor) mapTrustlineFlagsToStrings(flags xdr.TrustLineFlags) []string {
	var flagStrings []string

	if flags.IsAuthorized() {
		flagStrings = append(flagStrings, AuthorizedFlagName)
	}

	if flags.IsAuthorizedToMaintainLiabilitiesFlag() {
		flagStrings = append(flagStrings, AuthorizedToMaintainLiabilitiesFlagName)
	}

	if flags.IsClawbackEnabledFlag() {
		flagStrings = append(flagStrings, ClawbackEnabledFlagName)
	}

	return flagStrings
}

// parseHomeDomain returns the account's home domain before and after the effect,
// with the empty string standing for an unset domain on either side. Both the
// account pre-image and the effect's new value are required; a missing one is a
// malformed effect.
func (p *EffectsProcessor) parseHomeDomain(effect *EffectOutput, changes []ingest.Change) (oldDomain, newDomain string, err error) {
	prevLedgerEntryState := p.getPrevLedgerEntryState(effect, xdr.LedgerEntryTypeAccount, changes)
	if prevLedgerEntryState == nil {
		return "", "", fmt.Errorf("no previous account state for home domain effect on account %s (opID %d)", effect.Address, effect.OperationID)
	}
	newDomain, ok := effect.Details["home_domain"].(string)
	if !ok {
		return "", "", fmt.Errorf("home domain effect on account %s (opID %d) carries no new value", effect.Address, effect.OperationID)
	}
	return string(prevLedgerEntryState.Data.MustAccount().HomeDomain), newDomain, nil
}

// homeDomainChange derives the reason and key-value payload for a home-domain
// transition. The payload carries only the meaningful side of the transition, so
// the empty string never reaches the database: setting a domain on an account that
// had none carries just "new", removing one carries just "old", and replacing one
// carries both. A SetOptions operation may write the domain the account already
// has, which changes nothing and produces no state change (changed is false).
func homeDomainChange(oldDomain, newDomain string) (reason types.StateChangeReason, keyValue map[string]any, changed bool) {
	switch {
	case oldDomain == newDomain:
		return "", nil, false
	case oldDomain == "":
		return types.StateChangeReasonSet, map[string]any{"new": newDomain}, true
	case newDomain == "":
		return types.StateChangeReasonClear, map[string]any{"old": oldDomain}, true
	default:
		return types.StateChangeReasonUpdate, map[string]any{"old": oldDomain, "new": newDomain}, true
	}
}

// parseDataEntryValues extracts a changed data entry's values into a flat key-value
// payload carrying only the meaningful side of the change: a creation carries just
// "new", a removal just "old", an update both. Old values are recovered from the
// entry's pre-image; an effect whose pre-image is missing is malformed and rejected,
// so a value absent from the payload is always semantic rather than a reconstruction
// miss.
func (p *EffectsProcessor) parseDataEntryValues(effect *EffectOutput, effectType EffectType, changes []ingest.Change) (map[string]any, error) {
	keyValueMap := map[string]any{}
	if _, ok := effect.Details["name"].(xdr.String64); !ok {
		return nil, fmt.Errorf("data entry effect on account %s (opID %d) carries no name", effect.Address, effect.OperationID)
	}

	// The GraphQL schema declares the value non-null on additions and updates,
	// so a create/update effect without a new value is malformed.
	//exhaustive:ignore
	switch effectType {
	case EffectDataCreated, EffectDataUpdated:
		value, ok := effect.Details["value"]
		if !ok {
			return nil, fmt.Errorf("%s effect on account %s (opID %d) carries no new value", effect.TypeString, effect.Address, effect.OperationID)
		}
		keyValueMap["new"] = value
	}
	//exhaustive:ignore
	switch effectType {
	case EffectDataUpdated, EffectDataRemoved:
		prevLedgerEntryState := p.getPrevLedgerEntryState(effect, xdr.LedgerEntryTypeData, changes)
		if prevLedgerEntryState == nil {
			return nil, fmt.Errorf("no previous data entry state for %s effect on account %s (opID %d)", effect.TypeString, effect.Address, effect.OperationID)
		}
		oldData := prevLedgerEntryState.Data.MustData().DataValue
		keyValueMap["old"] = base64.StdEncoding.EncodeToString(oldData)
	}

	return keyValueMap, nil
}

// parseFlags processes flag-related effects and creates separate state changes for set and cleared flags.
// Stellar flags can be either set (true) or cleared (false), and we track each change separately.
func (p *EffectsProcessor) parseFlags(flags []string, changeBuilder StateChangeBuilder, effect *EffectOutput) []types.StateChange {
	var setFlags, clearFlags []string

	for _, flag := range flags {
		if value, ok := effect.Details[flag]; ok {
			if value == true {
				setFlags = append(setFlags, flag)
			} else {
				clearFlags = append(clearFlags, flag)
			}
		}
	}

	var changes []types.StateChange
	if len(setFlags) > 0 {
		changes = append(changes, changeBuilder.
			WithReason(types.StateChangeReasonSet).
			WithFlags(setFlags).
			Build())
	}
	if len(clearFlags) > 0 {
		changes = append(changes, changeBuilder.
			WithReason(types.StateChangeReasonClear).
			WithFlags(clearFlags).
			Build())
	}

	return changes
}

func (p *EffectsProcessor) parseSigners(changeBuilder StateChangeBuilder, effect *EffectOutput, effectType EffectType, changes []ingest.Change) ([]types.StateChange, error) {
	signerPublicKey := effect.Details["public_key"].(string)
	weight, err := convertToInt32(effect.Details["weight"])
	if err != nil {
		return nil, fmt.Errorf("converting weight for signer effect: %w", err)
	}
	newWeight := int16(weight)

	//exhaustive:ignore
	switch effectType {
	case EffectSignerCreated:
		changeBuilder = changeBuilder.WithSigner(signerPublicKey, nil, &newWeight)
	case EffectSignerUpdated, EffectSignerRemoved:
		// The GraphQL schema declares oldWeight non-null on signer updates and
		// removals, so the previous weight must be recovered from the account
		// entry's pre-image; an effect without one is malformed.
		prevLedgerEntryState := p.getPrevLedgerEntryState(effect, xdr.LedgerEntryTypeAccount, changes)
		if prevLedgerEntryState == nil {
			return nil, fmt.Errorf("no previous account state for signer %s effect on account %s (opID %d)", effect.TypeString, effect.Address, effect.OperationID)
		}
		prevAccount := prevLedgerEntryState.Data.MustAccount()
		oldSignerSummary := prevAccount.SignerSummary()
		oldVal, ok := oldSignerSummary[signerPublicKey]
		if !ok {
			// SignerSummary omits the master key when its weight is 0, so for the
			// master key "absent from the summary" means a prior weight of 0. Any
			// other signer must appear in the pre-image for an update/removal.
			if signerPublicKey != effect.Address {
				return nil, fmt.Errorf("signer %s missing from previous account state of %s (opID %d)", signerPublicKey, effect.Address, effect.OperationID)
			}
			oldVal = 0
		}
		oldWeight := int16(oldVal)
		if effectType == EffectSignerUpdated {
			changeBuilder = changeBuilder.WithSigner(signerPublicKey, &oldWeight, &newWeight)
		} else {
			changeBuilder = changeBuilder.WithSigner(signerPublicKey, &oldWeight, nil)
		}
	}
	return []types.StateChange{changeBuilder.Build()}, nil
}

// parseThresholds processes threshold-related effects and creates state changes for each threshold type.
// It extracts both old and new threshold values from the ledger entry changes. The GraphQL schema
// declares oldThreshold non-null, so a threshold effect without an account pre-image is malformed.
func (p *EffectsProcessor) parseThresholds(changeBuilder StateChangeBuilder, effect *EffectOutput, changes []ingest.Change) ([]types.StateChange, error) {
	// Find the account entry change to get old threshold values
	prevLedgerEntryState := p.getPrevLedgerEntryState(effect, xdr.LedgerEntryTypeAccount, changes)
	if prevLedgerEntryState == nil {
		return nil, fmt.Errorf("no previous account state for threshold effect on account %s (opID %d)", effect.Address, effect.OperationID)
	}
	prevAccount := prevLedgerEntryState.Data.MustAccount()

	// Create a separate state change for each threshold that was modified, in a fixed
	// order so ordinal assignment is deterministic when multiple thresholds change together.
	var thresholdChanges []types.StateChange
	for _, threshold := range thresholdOrder {
		level := thresholdToLevelMap[threshold]
		if value, ok := effect.Details[threshold]; ok {
			// Convert XDR threshold value to int16 for storage
			newValue := int16(value.(xdr.Uint32))

			var oldVal int16
			switch threshold {
			case "low_threshold":
				oldVal = int16(prevAccount.Thresholds[lowThresholdIndex])
			case "med_threshold":
				oldVal = int16(prevAccount.Thresholds[medThresholdIndex])
			case "high_threshold":
				oldVal = int16(prevAccount.Thresholds[highThresholdIndex])
			}

			thresholdChanges = append(thresholdChanges, changeBuilder.
				WithReason(types.StateChangeReasonUpdate).
				WithThresholdLevel(level).
				WithThreshold(&oldVal, &newValue).
				Build())
		}
	}
	return thresholdChanges, nil
}

// getPrevLedgerEntryState gets the previous ledger entry state for the specified ledger entry type.
func (p *EffectsProcessor) getPrevLedgerEntryState(effect *EffectOutput, ledgerEntryType xdr.LedgerEntryType, changes []ingest.Change) *xdr.LedgerEntry {
	for _, change := range changes {
		if change.Type != ledgerEntryType || change.Pre == nil {
			continue
		}
		pre := change.Pre
		// Match the entry to the effect's entity: an operation's change set can
		// carry several entries of the same type (merges touch two accounts; an
		// operation can touch several trustlines), and serving another entity's
		// pre-image would fabricate old values.
		//exhaustive:ignore
		switch ledgerEntryType {
		case xdr.LedgerEntryTypeAccount:
			if pre.Data.MustAccount().AccountId.Address() != effect.Address {
				continue
			}
		case xdr.LedgerEntryTypeTrustline:
			if !trustlineEntryMatchesEffect(pre.Data.MustTrustLine(), effect) {
				continue
			}
		case xdr.LedgerEntryTypeData:
			name, ok := effect.Details["name"].(xdr.String64)
			if !ok {
				continue
			}
			data := pre.Data.MustData()
			if data.AccountId.Address() != effect.Address || data.DataName != name {
				continue
			}
		}
		return pre
	}
	return nil
}

// trustlineEntryMatchesEffect reports whether the trustline entry belongs to the
// effect's trustor and references the effect's asset (or its liquidity pool for
// pool-share trustlines).
func trustlineEntryMatchesEffect(trustline xdr.TrustLineEntry, effect *EffectOutput) bool {
	if trustline.AccountId.Address() != effect.Address {
		return false
	}
	assetType, err := safeStringFromDetails(effect.Details, "asset_type")
	if err != nil {
		return false
	}

	if assetType == "liquidity_pool_shares" {
		if trustline.Asset.Type != xdr.AssetTypeAssetTypePoolShare {
			return false
		}
		poolID, err := safeStringFromDetails(effect.Details, "liquidity_pool_id")
		if err != nil {
			return false
		}
		return xdr.Hash(trustline.Asset.MustLiquidityPoolId()).HexString() == poolID
	}

	if trustline.Asset.Type == xdr.AssetTypeAssetTypePoolShare {
		return false
	}
	assetCode, err := safeStringFromDetails(effect.Details, "asset_code")
	if err != nil {
		return false
	}
	assetIssuer, err := safeStringFromDetails(effect.Details, "asset_issuer")
	if err != nil {
		return false
	}
	expected, err := xdr.NewCreditAsset(assetCode, assetIssuer)
	if err != nil {
		return false
	}
	return trustline.Asset.ToAsset().Equals(expected)
}
